"""Siege target scores: Annex value per cost (specials, map centre, compactness, spice opening, Fremen rings,
bunker pairs), retry / stuck / unreach drops, annex-keep and the swap to an affordable pick (`build_scoring`)."""
from rules.common import *  # noqa: F401,F403  thresholds (AI-POLICY §4) and bytecode helpers


def _annex_value(fb, b, cx, helpers, res, mine, mn):
    """Annex only (k = arg 2): value per cost on top of vanilla's score (closure f40995: -10 / zone of distance,
    resource fields in the zone (SpiceArea 40, others 10), region aiWeight (specials 20, Pole 40), main-base
    proximity x Outpost_DistanceCost_MRatio, owned neighbours x 10, +100 for a spice village while we own none; no
    annex cost at all, and tryAction then reserves Authority and waits when the pick is unaffordable). For each
    positive score: vanilla's per-zone distance counts VAN_HOPS_CAP zones at most (the rest added back); + the special
    table (ANNEX_SPECIALS by region id x faction, ANNEX_SPECIALS_EARLY while we own < ANNEX_SP_EARLY_N villages,
    ANNEX_SPECIAL for an unlisted special, Smugglers capped at ANNEX_SP_SMUG_CAP), + ANNEX_SIETCH with a sietch in
    the zone (Zone.getSietch); SPICE_ANY factions lose vanilla's first-spice +100; x (1 + CENTER_W x closeness to the
    map centre = mean village position, 0 at the farthest village; none within CENTER_BASE_R of another faction's main
    base; not for factions without Annex distance cost: Smugglers); factions with distance annex costs x the NEAR_W compactness factor (distance to our nearest structure on our
    land; applied after the ring terms, never below 1 for a feasible ring village: aimod_ddhold); x cmin / cost (real Authority cost: siege.getOccupationActionCost("Annex"), cmin = cheapest candidate:
    a village costing 2 cheap ones counts half); a spice village while we own none x ANNEX_SPICE1 (not SPICE_ANY);
    Fremen deep desert (Zone.updateOwner: a deep desert goes to the single owner of every neighbour with a village
    or main base, if it has DeepDesert_Surounded_GainControl): x (1 + w x min(DD_CAP, sum over unowned deep
    deserts next to the candidate of chance / (1 + neighbours still missing after it))), w = DD_W with the
    attribute, DD_W_PRE for Fremen before it; chance x DD_ENEMY per missing neighbour owned by another faction and
    per one within DD_BASE_R of another faction's main base; 0 when another faction's main base zone borders it;
    x DD_LINK when the candidate borders none of our non-deep-desert zones (reaching it means crossing desert);
    then + DD_ADD x best chance x w (x DD_LINK, x cmin / cost): a flat bonus like ANNEX_SPECIAL. floor ANNEX_FLOOR.
    Focus ring: lowest rank = villages missing (one within DD_BASE_R of another faction's main base or with an at-war
    stack at it, aimod_threat within LOCAL, counts twice) + hops from our main base; the nearer on a tie. A missing
    village under at-war threat also halves the ring's chance (DD_ENEMY), like one held by another faction. Logs `acand` per candidate (v0, hops, sp, cf, cen, dd, c, cmin, s) once per ASCORE_T per faction.
    Top 3: when the best scored is unaffordable now (AIController.getMissingResources of its cost at priority 3 non-empty)
    and the 2nd or 3rd is affordable, the unaffordable ones above it get 0.99 / 0.98 x its score (log `aswap` from, to,
    s); none affordable: vanilla reserves Authority and waits on the best, for ASWAP_WAIT s at most (map `aswt` faction
    -> since when the best is unaffordable): then the best affordable candidate anywhere, every one scored above it
    to 0.98 x its score (log `aswap` with wait). Never the pressed village. Ring hold (same factions): a candidate next to an unowned deep desert is a ring village (map
    'dring' -> now); when a candidate is on an uncontested ring in progress (aimod_ddhold) with fewer than DD_TRIES
    Annex launches (map 'dtries', counted by the launch gate), or one of our armies runs an Annex order on such a
    village, every candidate that isn't a ring village is dropped (Fremen Adur: the spice village was annexed while
    the ring around the uncontested desert was open; dropped, raid pillages it instead). Logs `ascore` (ASCORE_T per
    faction): tgt = our best, s, c (its cost), cmin, vb = vanilla's best (before this), v0 its vanilla score, vs =
    its score now, n candidates, hold = candidates dropped by the ring hold (never the director's pressed village)."""
    fac = 1
    fb.op('JNotEq', a=b.call('String.__compare', 2, fb.dyn(fb.string('Annex'))), b=b.const('i32', 0), offset='end')
    n = b.field(0, 'length')
    zero, big = b.const('f64', 0), b.const('f64', 1 << 30)
    zi = b.const('i32', 0)
    i, j = fb.reg(cx.t('i32')), fb.reg(cx.t('i32'))
    sc, c, cmin, q, d, dm, aw, v0 = (fb.reg(cx.t('f64')) for _ in range(8))
    se, te = fb.reg(cx.t('ent.Entity')), fb.reg(cx.t('ent.Entity'))
    annex = fb.string('Annex')
    gav = cx.fn('ent.Object.getAtbVal')
    gat = [a.value for a in cx.code.types[gav.type.value].definition.args]
    gref, gfac = fb.reg(gat[2]), fb.reg(gat[3])
    fb.op('Null', dst=gref)
    fb.op('Null', dst=gfac)
    gobj = fb.reg(gat[0])
    fb.op('Mov', dst=gobj, src=fac)
    dcr = fb.reg(cx.t('f64'))
    fb.op('Call4', dst=dcr, fun=gav.findex.value, arg0=gobj, arg1=b.const('i32', 952), arg2=gref, arg3=gfac)
    # SPICE_ANY faction? first spice village owned?
    exempt = fb.reg(cx.t('bool'))
    fb.op('Bool', dst=exempt, value=False)
    kd = b.field(fac, 'kind')
    fb.op('JNull', reg=kd, offset='an_kd')
    for nm in SPICE_ANY:
        lbl = _uid('sx')
        fb.op('JNotEq', a=b.call('String.__compare', kd, fb.dyn(fb.string(nm))), b=zi, offset=lbl)
        fb.op('Bool', dst=exempt, value=True)
        fb.label(lbl)
    fb.label('an_kd')
    nsp = fb.reg(cx.t('i32'))
    fb.op('Mov', dst=nsp, src=b.const('i32', 1))
    nsd = fb.get(fac, 'cacheData', 'numSpiceVillages')
    fb.op('JNull', reg=nsd, offset='an_nsp')
    fb.op('SafeCast', dst=nsp, src=nsd)
    fb.label('an_nsp')
    # Fremen deep desert weight: DD_W with DeepDesert_Surounded_GainControl, DD_W_PRE for Fremen before it
    ddw, dd, con, miss, bdd, cmx = (fb.reg(cx.t('f64')) for _ in range(6))
    fb.op('Mov', dst=ddw, src=zero)
    fb.op('Mov', dst=dd, src=zero)
    fb.op('Mov', dst=bdd, src=zero)
    one_f, den = _ratio(fb, b, 1), _ratio(fb, b, DD_ENEMY)
    k1, k2, k3, k4 = (fb.reg(cx.t('i32')) for _ in range(4))
    hm = fb.reg(cx.t('bool'))
    hmb = cx.fn('ent.Zone.hasMainBase')
    hnull = fb.reg(cx.code.types[hmb.type.value].definition.args[1].value)
    fb.op('Null', dst=hnull)
    ddc = helpers['ddhold']
    now = fb.reg(cx.t('f64'))
    fb.op('Mov', dst=now, src=b.field(_state(fb, b, cx), 'time'))
    dring, dtries = _global_map(fb, b, cx, 'dring'), _global_map(fb, b, cx, 'dtries')
    hold, isr, cln = fb.reg(cx.t('bool')), fb.reg(cx.t('bool')), fb.reg(cx.t('bool'))
    fb.op('Bool', dst=hold, value=False)
    nh = fb.reg(cx.t('i32'))
    fb.op('Mov', dst=nh, src=b.const('i32', 0))
    brest = fb.reg(cx.t('ent.Entity'))
    fb.op('Null', dst=brest)
    brs, brc, brdd, trq = (fb.reg(cx.t('f64')) for _ in range(4))
    for r in (brs, brc, brdd):
        fb.op('Mov', dst=r, src=b.const('f64', 0))
    has = cx.fn('ent.Object.hasAttribute')
    hat = [a.value for a in cx.code.types[has.type.value].definition.args]
    href, hfac = fb.reg(hat[2]), fb.reg(hat[3])
    fb.op('Null', dst=href)
    fb.op('Null', dst=hfac)
    hres = fb.reg(cx.t('bool'))
    fb.op('Call4', dst=hres, fun=has.findex.value, arg0=gobj, arg1=b.const('i32', DD_ATB), arg2=href, arg3=hfac)
    fb.op('JFalse', cond=hres, offset='an_dpre')
    fb.op('Mov', dst=ddw, src=_ratio(fb, b, DD_W))
    fb.op('JAlways', offset='an_dw')
    fb.label('an_dpre')
    fb.op('JNull', reg=kd, offset='an_dw')
    fb.op('JNotEq', a=b.call('String.__compare', kd, fb.dyn(fb.string('Fremen'))), b=zi, offset='an_dw')
    fb.op('Mov', dst=ddw, src=_ratio(fb, b, DD_W_PRE))
    fb.label('an_dw')
    # the ring we work on (lowest rank = villages missing + hops: see an_hok) among unowned deep deserts next to a village that no
    # other faction's main base borders and whose missing villages are all neutral (a held one stalls the ring: it
    # must not halve a clean one); tie: fewest villages missing; the others count x DD_FAR (one ring at a time, not
    # two half-done). No such desert: no focus penalty (hmin 999)
    gdb = cx.fn('ent.Zone.getDistanceToPlayerBase')
    gnull = fb.reg(cx.code.types[gdb.type.value].definition.args[2].value)
    fb.op('Null', dst=gnull)
    hmin, hz = fb.reg(cx.t('i32')), fb.reg(cx.t('i32'))
    fb.op('Mov', dst=hmin, src=b.const('i32', 999))
    mmin, hmis = fb.reg(cx.t('f64')), fb.reg(cx.t('f64'))  # mmin = the focus ring's rank (an_hok)
    hthr = fb.reg(cx.t('f64'))
    threat = helpers['threat']
    local_r = b.const('f64', LOCAL)
    fb.op('Mov', dst=mmin, src=big)
    fb.op('JSLte', a=ddw, b=zero, offset='an_hm')
    facs0 = b.cast(fb.get(_state(fb, b, cx), 'factions', 'array'), 'hl.types.ArrayObj')
    k5, k6 = fb.reg(cx.t('i32')), fb.reg(cx.t('i32'))
    hvv = fb.reg(cx.t('ent.Entity'))
    hvl = b.field(_state(fb, b, cx), 'villages')
    fb.op('JNull', reg=hvl, offset='an_hm')
    fb.op('Mov', dst=k1, src=zi)
    b.loop_head('an_hv')
    fb.op('JSGte', a=k1, b=b.field(hvl, 'length'), offset='an_hm')
    hv = b.cast(b.call('hl.types.ArrayObj.getDyn', hvl, k1), 'ent.Entity')
    fb.op('Incr', dst=k1)
    fb.op('JNull', reg=hv, offset='an_hv')
    hvz = b.call('ent.Entity.get_zone', hv)
    fb.op('JNull', reg=hvz, offset='an_hv')
    hvn = b.field(hvz, 'neighbors')
    fb.op('JNull', reg=hvn, offset='an_hv')
    fb.op('Mov', dst=k2, src=zi)
    b.loop_head('an_hw')
    fb.op('JSGte', a=k2, b=b.field(hvn, 'length'), offset='an_hv')
    hdz = b.cast(b.call('hl.types.ArrayObj.getDyn', hvn, k2), 'ent.Zone')
    fb.op('Incr', dst=k2)
    fb.op('JNull', reg=hdz, offset='an_hw')
    fb.op('JFalse', cond=b.call('ent.Zone.isDeepDesert', hdz), offset='an_hw')
    fb.op('JEq', a=b.field(hdz, 'owner'), b=fac, offset='an_hw')
    fb.op('Call3', dst=hz, fun=gdb.findex.value, arg0=hdz, arg1=fac, arg2=gnull)
    hdn = b.field(hdz, 'neighbors')
    fb.op('JNull', reg=hdn, offset='an_hw')
    fb.op('Mov', dst=hmis, src=zero)
    fb.op('Mov', dst=k3, src=zi)
    b.loop_head('an_hx')
    fb.op('JSGte', a=k3, b=b.field(hdn, 'length'), offset='an_hok')
    hmz = b.cast(b.call('hl.types.ArrayObj.getDyn', hdn, k3), 'ent.Zone')
    fb.op('Incr', dst=k3)
    fb.op('JNull', reg=hmz, offset='an_hx')
    fb.op('JEq', a=b.field(hmz, 'owner'), b=fac, offset='an_hx')
    fb.op('Call2', dst=hm, fun=hmb.findex.value, arg0=hmz, arg1=hnull)
    fb.op('JTrue', cond=hm, offset='an_hw')
    fb.op('JNull', reg=b.call('ent.Zone.getVillage', hmz), offset='an_hx')
    fb.op('JNotNull', reg=b.field(hmz, 'owner'), offset='an_hw')  # another faction holds one: stalled, no focus
    fb.op('Add', dst=hmis, a=hmis, b=one_f)
    # a missing village within DD_BASE_R of another faction's main base counts twice (the far end of the map next
    # to its capital: progress there stalls)
    fb.op('JNull', reg=facs0, offset='an_hx')
    fb.op('Mov', dst=hvv, src=b.cast(b.call('ent.Zone.getVillage', hmz), 'ent.Entity'))
    fb.op('JNull', reg=hvv, offset='an_hx')
    _unreach(fb, b, cx, hvv, now, 'an_hw', 1)  # a missing village out of supply reach: this ring can't close, no focus
    # contested: an at-war stack at (or heading to) it counts one more (Fremen's near ring stalled on Aish-Al'nit, 100
    # from Tabr, while Smugglers' 9 armies stood 216-360 from it; vanilla wanted 12 armies there)
    fb.op('Call3', dst=hthr, fun=threat, arg0=fac, arg1=hvv, arg2=local_r)
    fb.op('JSLte', a=hthr, b=zero, offset='an_hnc')
    fb.op('Add', dst=hmis, a=hmis, b=one_f)
    fb.label('an_hnc')
    fb.op('Mov', dst=k5, src=zi)
    b.loop_head('an_hf')
    fb.op('JSGte', a=k5, b=b.field(facs0, 'length'), offset='an_hx')
    hof = b.cast(b.call('hl.types.ArrayObj.getDyn', facs0, k5), 'ent.Faction')
    fb.op('Incr', dst=k5)
    fb.op('JNull', reg=hof, offset='an_hf')
    fb.op('JEq', a=hof, b=fac, offset='an_hf')
    hmbs = b.field(hof, 'mainBases')
    fb.op('JNull', reg=hmbs, offset='an_hf')
    fb.op('Mov', dst=k6, src=zi)
    b.loop_head('an_hg')
    fb.op('JSGte', a=k6, b=b.field(hmbs, 'length'), offset='an_hf')
    hmb2 = b.cast(b.call('hl.types.ArrayObj.getDyn', hmbs, k6), 'ent.Entity')
    fb.op('Incr', dst=k6)
    fb.op('JNull', reg=hmb2, offset='an_hg')
    fb.op('JSGt', a=b.call('ent.Entity.getDistTo', hvv, hmb2), b=b.const('f64', DD_BASE_R), offset='an_hg')
    fb.op('Add', dst=hmis, a=hmis, b=one_f)
    fb.op('JAlways', offset='an_hx')
    fb.label('an_hok')
    # rank = villages missing (one near another faction's main base or under at-war threat counts twice) + hops from
    # our main base: overall the cheapest ring to close, the nearer one on a tie (user: Fremen worked on a ring whose
    # far end was contested while a nearer desert was the better choice). Every desert is ranked (no order-dependent
    # pruning by hops)
    hzf = fb.reg(cx.t('f64'))
    fb.op('ToSFloat', dst=hzf, src=hz)
    fb.op('Add', dst=hzf, a=hzf, b=hmis)
    fb.op('JSLt', a=hzf, b=mmin, offset='an_hset')
    fb.op('JSGt', a=hzf, b=mmin, offset='an_hw')
    fb.op('JSGte', a=hz, b=hmin, offset='an_hw')
    fb.label('an_hset')
    fb.op('Mov', dst=hmin, src=hz)
    fb.op('Mov', dst=mmin, src=hzf)
    fb.op('JAlways', offset='an_hw')
    fb.label('an_hm')
    facs = b.cast(fb.get(_state(fb, b, cx), 'factions', 'array'), 'hl.types.ArrayObj')
    oc = cx.fn('ent.comp.SiegeComponent.getOccupationActionCost')
    oat = [a.value for a in cx.code.types[oc.type.value].definition.args]
    onull = fb.reg(oat[2])
    fb.op('Null', dst=onull)

    def cost_of(st, dst):
        """dst = sum of qty of st's Annex costs for us (0 if unknown)."""
        lbl = _uid('co')
        fb.op('Mov', dst=dst, src=zero)
        sg = b.field(st, 'siege')
        fb.op('JNull', reg=sg, offset=lbl)
        arr = fb.reg(cx.code.types[oc.type.value].definition.ret.value)
        fb.op('Call4', dst=arr, fun=oc.findex.value, arg0=sg, arg1=annex, arg2=onull, arg3=fac)
        fb.op('JNull', reg=arr, offset=lbl)
        k = fb.reg(cx.t('i32'))
        fb.op('Mov', dst=k, src=zi)
        head = _uid('cl')
        b.loop_head(head)
        fb.op('JSGte', a=k, b=b.field(arr, 'length'), offset=lbl)
        qd = fb.get(b.call('hl.types.ArrayObj.getDyn', arr, k), 'qty')
        fb.op('Incr', dst=k)
        fb.op('JNull', reg=qd, offset=head)
        fb.op('SafeCast', dst=q, src=qd)
        fb.op('Add', dst=dst, a=dst, b=q)
        fb.op('JAlways', offset=head)
        fb.label(lbl)

    # map centre = mean village position; crad = the farthest village from it (closeness 0 there)
    cxm, cym, crad, cnt = (fb.reg(cx.t('f64')) for _ in range(4))
    for r in (cxm, cym, crad, cnt):
        fb.op('Mov', dst=r, src=zero)
    cvl = b.field(_state(fb, b, cx), 'villages')
    fb.op('JNull', reg=cvl, offset='cen_d')
    fb.op('Mov', dst=k1, src=zi)
    b.loop_head('cen_a')
    fb.op('JSGte', a=k1, b=b.field(cvl, 'length'), offset='cen_b')
    cv1 = b.cast(b.call('hl.types.ArrayObj.getDyn', cvl, k1), 'ent.Entity')
    fb.op('Incr', dst=k1)
    fb.op('JNull', reg=cv1, offset='cen_a')
    fb.op('Add', dst=cxm, a=cxm, b=b.field(cv1, 'posx'))
    fb.op('Add', dst=cym, a=cym, b=b.field(cv1, 'posy'))
    fb.op('Add', dst=cnt, a=cnt, b=one_f)
    fb.op('JAlways', offset='cen_a')
    fb.label('cen_b')
    fb.op('JSLte', a=cnt, b=zero, offset='cen_d')
    fb.op('SDiv', dst=cxm, a=cxm, b=cnt)
    fb.op('SDiv', dst=cym, a=cym, b=cnt)
    fb.op('Mov', dst=k1, src=zi)
    b.loop_head('cen_c')
    fb.op('JSGte', a=k1, b=b.field(cvl, 'length'), offset='cen_d')
    cv2 = b.cast(b.call('hl.types.ArrayObj.getDyn', cvl, k1), 'ent.Entity')
    fb.op('Incr', dst=k1)
    fb.op('JNull', reg=cv2, offset='cen_c')
    fb.op('Sub', dst=d, a=b.field(cv2, 'posx'), b=cxm)
    fb.op('Mul', dst=d, a=d, b=d)
    fb.op('Sub', dst=q, a=b.field(cv2, 'posy'), b=cym)
    fb.op('Mul', dst=q, a=q, b=q)
    fb.op('Add', dst=d, a=d, b=q)
    fb.op('JSLte', a=d, b=crad, offset='cen_c')
    fb.op('Mov', dst=crad, src=d)
    fb.op('JAlways', offset='cen_c')
    fb.label('cen_d')
    fb.op('Mov', dst=crad, src=b.call('hxd.$Math.sqrt', crad))
    nvil = fb.reg(cx.t('i32'))
    fb.op('Mov', dst=nvil, src=b.field(b.call('ent.Faction.getVillages', fac), 'length'))
    # per-candidate breakdown in this call? (`acand`, once per ASCORE_T per faction)
    logc = fb.reg(cx.t('bool'))
    fb.op('Bool', dst=logc, value=False)
    _throttle(fb, b, cx, 'acand', fac, ASCORE_T, 'acn')
    fb.op('Bool', dst=logc, value=True)
    fb.label('acn')
    vo, spb, cf, cenf, hcf = (fb.reg(cx.t('f64')) for _ in range(5))
    for r in (vo, spb, hcf):
        fb.op('Mov', dst=r, src=zero)
    for r in (cf, cenf):
        fb.op('Mov', dst=r, src=one_f)
    hz2, hzx = fb.reg(cx.t('i32')), fb.reg(cx.t('i32'))
    mx2 = fb.reg(cx.t('f64'))
    fb.op('Mov', dst=hz2, src=zi)
    feas = fb.reg(cx.t('bool'))
    # pass 1: cheapest candidate cost, vanilla's best
    vb = fb.reg(cx.t('ent.Entity'))
    fb.op('Null', dst=vb)
    fb.op('Mov', dst=v0, src=zero)
    fb.op('Mov', dst=cmin, src=big)
    fb.op('Mov', dst=i, src=zi)
    b.loop_head('an1')
    fb.op('JSGte', a=i, b=n, offset='an1d')
    s = b.cast(b.call('hl.types.ArrayObj.getDyn', 0, i), 'ent.Structure')
    fb.op('Incr', dst=i)
    fb.op('JNull', reg=s, offset='an1')
    fb.op('Mov', dst=se, src=s)
    v = b.call('haxe.ds.ObjectMap.get', res, fb.dyn(se))
    fb.op('JNull', reg=v, offset='an1')
    fb.op('SafeCast', dst=sc, src=v)
    fb.op('JEq', a=sc, b=zero, offset='an1')  # 0: vanilla's invalid target; negative: far (hop cap below)
    fb.op('JSLte', a=sc, b=v0, offset='an1c')
    fb.op('Mov', dst=v0, src=sc)
    fb.op('Mov', dst=vb, src=se)
    fb.label('an1c')
    cost_of(s, c)
    fb.op('JSLte', a=c, b=zero, offset='an1')
    fb.op('JSGte', a=c, b=cmin, offset='an1')
    fb.op('Mov', dst=cmin, src=c)
    fb.op('JAlways', offset='an1')
    fb.label('an1d')
    # Annex reserve: the cheapest candidate's Authority cost per faction (maps `acmin` / `acmt` time), read by the
    # Underworld HQ cap (rules/uhq.py) so escalating HQ installs don't eat the next Annex
    acm_lbl = _uid('an_acm')
    fb.op('JSGte', a=cmin, b=big, offset=acm_lbl)
    b.call('haxe.ds.ObjectMap.set', _global_map(fb, b, cx, 'acmin'), fb.dyn(fac), fb.dyn(cmin))
    acmt_now = fb.reg(cx.t('f64'))
    fb.op('Mov', dst=acmt_now, src=b.field(_state(fb, b, cx), 'time'))
    b.call('haxe.ds.ObjectMap.set', _global_map(fb, b, cx, 'acmt'), fb.dyn(fac), fb.dyn(acmt_now))
    fb.label(acm_lbl)
    # pass 2: rescore
    best = fb.reg(cx.t('ent.Entity'))
    fb.op('Null', dst=best)
    bs, bc = fb.reg(cx.t('f64')), fb.reg(cx.t('f64'))
    fb.op('Mov', dst=bs, src=zero)
    fb.op('Mov', dst=bc, src=zero)
    hs = fb.reg(cx.t('bool'))
    fb.op('Mov', dst=i, src=zi)
    b.loop_head('an2')
    fb.op('JSGte', a=i, b=n, offset='an2d')
    s2 = b.cast(b.call('hl.types.ArrayObj.getDyn', 0, i), 'ent.Structure')
    fb.op('Incr', dst=i)
    fb.op('JNull', reg=s2, offset='an2')
    fb.op('Mov', dst=se, src=s2)
    v2 = b.call('haxe.ds.ObjectMap.get', res, fb.dyn(se))
    fb.op('JNull', reg=v2, offset='an2')
    fb.op('SafeCast', dst=sc, src=v2)
    fb.op('JEq', a=sc, b=zero, offset='an2')  # vanilla's invalid target
    z = b.call('ent.Entity.get_zone', se)
    fb.op('JNull', reg=z, offset='an2')
    fb.op('Mov', dst=vo, src=sc)
    # vanilla's -10 per zone from our main base counts VAN_HOPS_CAP zones at most: add back the rest, before the
    # positivity test (a far plain village scores <= 0 in vanilla: the cap must lift exactly those). Not for a
    # faction without Annex distance cost (Smugglers: the per-zone score is its only brake on spreading), not for
    # getDistanceToPlayerBase's 99 (no main base)
    fb.op('Mov', dst=hz2, src=zi)
    fb.op('JSLte', a=dcr, b=zero, offset='an_hcap')
    fb.op('Call3', dst=hz2, fun=gdb.findex.value, arg0=z, arg1=fac, arg2=gnull)
    fb.op('JSGte', a=hz2, b=b.const('i32', 99), offset='an_hcap')
    fb.op('JSLte', a=hz2, b=b.const('i32', VAN_HOPS_CAP), offset='an_hcap')
    fb.op('Sub', dst=hzx, a=hz2, b=b.const('i32', VAN_HOPS_CAP))
    fb.op('ToSFloat', dst=hcf, src=hzx)
    fb.op('Mul', dst=hcf, a=hcf, b=b.const('f64', 10))
    fb.op('Add', dst=sc, a=sc, b=hcf)
    fb.label('an_hcap')
    # still not positive: vanilla's (unpicked) score stands, except for a village of an uncontested deep-desert ring in
    # progress (aimod_ddclean): it starts at ANNEX_FLOOR so the ring terms below can lift it (a plain village 3+ zones
    # out scores <= -29: Fremen's ring-closing Alifdad, neutral and unguarded, was never scored while windy specials
    # were annexed; logs `aring` f, v, v0)
    fb.op('JSGt', a=sc, b=zero, offset='an_pos')
    arc = fb.reg(cx.t('bool'))
    fb.op('Call2', dst=arc, fun=helpers['ddclean'], arg0=fac, arg1=z)
    fb.op('JFalse', cond=arc, offset='an2')
    fb.op('Mov', dst=sc, src=_ratio(fb, b, ANNEX_FLOOR))
    _throttle(fb, b, cx, 'aring', se, 60, 'an_pos')
    _log_ev(fb, b, cx, helpers, 'aring', [('f', fb.get(fac, 'kind')), ('v', se), ('v0', vo)])
    fb.label('an_pos')
    # special region: faction x region table (strategy GENERAL "Specials"; constants ANNEX_SPECIALS)
    fb.op('Mov', dst=spb, src=zero)
    rid = b.cast(fb.get(z, 'inf', 'id'), 'String')
    fb.op('JNull', reg=rid, offset='sp_fb')
    for _rid, (_base, _over) in ANNEX_SPECIALS.items():
        _nx = _uid('spn')
        fb.op('JNotEq', a=b.call('String.__compare', rid, fb.dyn(fb.string(_rid))), b=zi, offset=_nx)
        fb.op('Mov', dst=spb, src=b.const('f64', _base))
        fb.op('JNull', reg=kd, offset='sp_done')
        for _fn, _bo in _over.items():
            _ny = _uid('spf')
            fb.op('JNotEq', a=b.call('String.__compare', kd, fb.dyn(fb.string(_fn))), b=zi, offset=_ny)
            fb.op('Mov', dst=spb, src=b.const('f64', _bo))
            fb.op('JAlways', offset='sp_done')
            fb.label(_ny)
        fb.op('JAlways', offset='sp_done')
        fb.label(_nx)
    for _rid, (_early, _late) in ANNEX_SPECIALS_EARLY.items():
        _nx = _uid('spn')
        fb.op('JNotEq', a=b.call('String.__compare', rid, fb.dyn(fb.string(_rid))), b=zi, offset=_nx)
        fb.op('Mov', dst=spb, src=b.const('f64', _late))
        fb.op('JSGte', a=nvil, b=b.const('i32', ANNEX_SP_EARLY_N), offset='sp_done')
        fb.op('Mov', dst=spb, src=b.const('f64', _early))
        fb.op('JAlways', offset='sp_done')
        fb.label(_nx)
    fb.label('sp_fb')
    awd = fb.get(z, 'inf', 'props', 'aiWeight')
    fb.op('JNull', reg=awd, offset='sp_done')
    fb.op('SafeCast', dst=aw, src=awd)
    fb.op('JSLt', a=aw, b=b.const('f64', 20), offset='sp_done')
    fb.op('Mov', dst=spb, src=b.const('f64', ANNEX_SPECIAL))  # a special the table doesn't list
    fb.label('sp_done')
    fb.op('JNull', reg=kd, offset='sp_cap')
    fb.op('JNotEq', a=b.call('String.__compare', kd, fb.dyn(fb.string('Smugglers'))), b=zi, offset='sp_cap')
    fb.op('JSLte', a=spb, b=b.const('f64', ANNEX_SP_SMUG_CAP), offset='sp_cap')
    fb.op('Mov', dst=spb, src=b.const('f64', ANNEX_SP_SMUG_CAP))
    fb.label('sp_cap')
    fb.op('Add', dst=sc, a=sc, b=spb)
    # a sietch in the zone (neutral / hostile / ancient / accursed): a small flat bonus
    fb.op('JNull', reg=b.call('ent.Zone.getSietch', z), offset='an_nsi')
    fb.op('Add', dst=sc, a=sc, b=b.const('f64', ANNEX_SIETCH))
    fb.label('an_nsi')
    # first spice village: SPICE_ANY factions lose vanilla's +100
    fb.op('Mov', dst=hs, src=b.call('ent.Zone.hasSpice', z))
    fb.op('JFalse', cond=hs, offset='an_nsp1')
    fb.op('JSGte', a=nsp, b=b.const('i32', 1), offset='an_nsp1')
    fb.op('JFalse', cond=exempt, offset='an_nsp1')
    fb.op('Sub', dst=sc, a=sc, b=b.const('f64', 100))
    fb.label('an_nsp1')
    # compactness (factions with distance annex costs): factor cf, applied after the deep-desert block (a feasible
    # Fremen ring isn't penalised for distance)
    fb.op('Mov', dst=cf, src=one_f)
    fb.op('JSLte', a=dcr, b=zero, offset='an_near')
    fb.op('Mov', dst=dm, src=big)
    fb.op('Mov', dst=j, src=zi)
    b.loop_head('an_m')
    fb.op('JSGte', a=j, b=mn, offset='an_md')
    t = b.cast(b.call('hl.types.ArrayObj.getDyn', mine, j), 'ent.Structure')
    fb.op('Incr', dst=j)
    fb.op('JNull', reg=t, offset='an_m')
    fb.op('Mov', dst=te, src=t)
    tz = b.call('ent.Entity.get_zone', te)
    fb.op('JNull', reg=tz, offset='an_m')
    fb.op('JNotEq', a=b.field(tz, 'owner'), b=fac, offset='an_m')
    fb.op('Mov', dst=d, src=b.call('ent.Entity.getDistTo', se, te))
    fb.op('JSGte', a=d, b=dm, offset='an_m')
    fb.op('Mov', dst=dm, src=d)
    fb.op('JAlways', offset='an_m')
    fb.label('an_md')
    fb.op('JSGte', a=dm, b=big, offset='an_near')
    ref = b.const('f64', NEAR_REF)
    fb.op('Sub', dst=q, a=ref, b=dm)
    fb.op('SDiv', dst=q, a=q, b=ref)
    fb.op('Mul', dst=q, a=q, b=_ratio(fb, b, NEAR_W))
    lo, hi = _ratio(fb, b, -NEAR_W), _ratio(fb, b, NEAR_W)
    fb.op('JSGte', a=q, b=lo, offset='an_lo')
    fb.op('Mov', dst=q, src=lo)
    fb.label('an_lo')
    fb.op('JSLte', a=q, b=hi, offset='an_hi')
    fb.op('Mov', dst=q, src=hi)
    fb.label('an_hi')
    fb.op('Add', dst=q, a=q, b=_ratio(fb, b, 1))
    fb.op('Mov', dst=cf, src=q)
    fb.label('an_near')
    # map centre: x (1 + CENTER_W x closeness), none within CENTER_BASE_R of another faction's main base; never for a
    # faction without Annex distance cost (Smugglers: user, their villages are islands, not a march to the middle)
    fb.op('Mov', dst=cenf, src=one_f)
    fb.op('JSLte', a=dcr, b=zero, offset='an_cen')
    fb.op('JSLte', a=crad, b=zero, offset='an_cen')
    fb.op('JNull', reg=facs, offset='an_cen')
    fb.op('Mov', dst=k3, src=zi)
    b.loop_head('an_cf')
    fb.op('JSGte', a=k3, b=b.field(facs, 'length'), offset='an_cok')
    cof = b.cast(b.call('hl.types.ArrayObj.getDyn', facs, k3), 'ent.Faction')
    fb.op('Incr', dst=k3)
    fb.op('JNull', reg=cof, offset='an_cf')
    fb.op('JEq', a=cof, b=fac, offset='an_cf')
    cmbs = b.field(cof, 'mainBases')
    fb.op('JNull', reg=cmbs, offset='an_cf')
    fb.op('Mov', dst=k4, src=zi)
    b.loop_head('an_cg')
    fb.op('JSGte', a=k4, b=b.field(cmbs, 'length'), offset='an_cf')
    cmb = b.cast(b.call('hl.types.ArrayObj.getDyn', cmbs, k4), 'ent.Entity')
    fb.op('Incr', dst=k4)
    fb.op('JNull', reg=cmb, offset='an_cg')
    fb.op('JSLte', a=b.call('ent.Entity.getDistTo', se, cmb), b=b.const('f64', CENTER_BASE_R), offset='an_cen')
    fb.op('JAlways', offset='an_cg')
    fb.label('an_cok')
    fb.op('Sub', dst=d, a=b.field(se, 'posx'), b=cxm)
    fb.op('Mul', dst=d, a=d, b=d)
    fb.op('Sub', dst=q, a=b.field(se, 'posy'), b=cym)
    fb.op('Mul', dst=q, a=q, b=q)
    fb.op('Add', dst=d, a=d, b=q)
    fb.op('Mov', dst=d, src=b.call('hxd.$Math.sqrt', d))
    fb.op('SDiv', dst=q, a=d, b=crad)
    fb.op('JSLte', a=q, b=one_f, offset='an_cq')
    fb.op('Mov', dst=q, src=one_f)
    fb.label('an_cq')
    fb.op('Sub', dst=q, a=one_f, b=q)
    fb.op('Mul', dst=q, a=q, b=_ratio(fb, b, CENTER_W))
    fb.op('Add', dst=cenf, a=one_f, b=q)
    fb.op('Mul', dst=sc, a=sc, b=cenf)
    fb.label('an_cen')
    # value per cost
    cost_of(s2, c)
    fb.op('JSGt', a=c, b=zero, offset='an_pc')
    # free (cost 0: Water Subsidies on Polar Sink): only an AI that can hold it, each for itself (rules/claim.py); only while
    # another candidate has a cost (everything free, or no cost known: nothing lures more than the rest)
    fb.op('JSGte', a=cmin, b=big, offset='an_nc')
    fcl = fb.reg(cx.t('bool'))
    fb.op('Call2', dst=fcl, fun=helpers['fclaim'], arg0=fac, arg1=s2)
    fb.op('JFalse', cond=logc, offset='an_fcl')
    _log_ev(fb, b, cx, helpers, 'fclaim', [('f', fb.get(fac, 'kind')), ('tgt', se), ('ok', fcl), ('s', sc)])
    fb.label('an_fcl')
    fb.op('JFalse', cond=fcl, offset='an_fdrop')
    fb.op('Add', dst=sc, a=sc, b=b.const('f64', CLAIM_ADD))
    fb.op('JAlways', offset='an_nc')
    fb.label('an_fdrop')
    b.call('haxe.ds.ObjectMap.remove', res, fb.dyn(se))
    fb.op('JAlways', offset='an2')
    fb.label('an_pc')
    fb.op('JSGte', a=cmin, b=big, offset='an_nc')
    fb.op('Mul', dst=sc, a=sc, b=cmin)
    fb.op('SDiv', dst=sc, a=sc, b=c)
    fb.label('an_nc')
    # neutral village under our main base's guns (BUNKER_R): x BUNKER_MB (no longer a hard redirect)
    mbs0 = b.field(fac, 'mainBases')
    fb.op('JNull', reg=mbs0, offset='an_mb')
    fb.op('Mov', dst=j, src=zi)
    b.loop_head('an_mbl')
    fb.op('JSGte', a=j, b=b.field(mbs0, 'length'), offset='an_mb')
    mb0 = b.cast(b.call('hl.types.ArrayObj.getDyn', mbs0, j), 'ent.Structure')
    fb.op('Incr', dst=j)
    fb.op('JNull', reg=mb0, offset='an_mbl')
    fb.op('JFalse', cond=b.call('ent.Structure.get_isActiveMainBase', mb0), offset='an_mbl')
    fb.op('Mov', dst=te, src=mb0)
    fb.op('JSGt', a=b.call('ent.Entity.getDistTo', se, te), b=b.const('f64', BUNKER_R), offset='an_mbl')
    fb.op('Mul', dst=sc, a=sc, b=_ratio(fb, b, BUNKER_MB))
    fb.label('an_mb')
    # opening: a spice field first
    fb.op('JFalse', cond=hs, offset='an_s1')
    fb.op('JSGte', a=nsp, b=b.const('i32', 1), offset='an_s1')
    fb.op('JTrue', cond=exempt, offset='an_s1')
    fb.op('Mul', dst=sc, a=sc, b=b.const('f64', ANNEX_SPICE1))
    fb.label('an_s1')
    # Fremen deep desert: surround it (all neighbours with a village / main base ours -> Zone.updateOwner gives it)
    fb.op('Bool', dst=isr, value=False)
    fb.op('JSLte', a=ddw, b=zero, offset='an_dd')
    fb.op('Mov', dst=dd, src=zero)
    fb.op('Mov', dst=cmx, src=zero)
    zn = b.field(z, 'neighbors')
    fb.op('JNull', reg=zn, offset='an_ddx')
    fb.op('Mov', dst=k1, src=zi)
    b.loop_head('an_d')
    fb.op('JSGte', a=k1, b=b.field(zn, 'length'), offset='an_ddx')
    dz = b.cast(b.call('hl.types.ArrayObj.getDyn', zn, k1), 'ent.Zone')
    fb.op('Incr', dst=k1)
    fb.op('JNull', reg=dz, offset='an_d')
    fb.op('JFalse', cond=b.call('ent.Zone.isDeepDesert', dz), offset='an_d')
    fb.op('JEq', a=b.field(dz, 'owner'), b=fac, offset='an_d')
    fb.op('Mov', dst=con, src=_ratio(fb, b, 1))
    fb.op('Call3', dst=hz, fun=gdb.findex.value, arg0=dz, arg1=fac, arg2=gnull)
    fb.op('Mov', dst=miss, src=zero)
    fb.op('Mov', dst=mx2, src=zero)
    dn = b.field(dz, 'neighbors')
    fb.op('JNull', reg=dn, offset='an_d')
    fb.op('Mov', dst=k2, src=zi)
    b.loop_head('an_e')
    fb.op('JSGte', a=k2, b=b.field(dn, 'length'), offset='an_ed')
    mz = b.cast(b.call('hl.types.ArrayObj.getDyn', dn, k2), 'ent.Zone')
    fb.op('Incr', dst=k2)
    fb.op('JNull', reg=mz, offset='an_e')
    fb.op('JEq', a=mz, b=z, offset='an_e')  # the candidate itself
    mo = b.field(mz, 'owner')
    fb.op('JEq', a=mo, b=fac, offset='an_e')
    fb.op('Call2', dst=hm, fun=hmb.findex.value, arg0=mz, arg1=hnull)
    fb.op('JTrue', cond=hm, offset='an_d')  # another faction's main base borders it: never ours
    mv = b.call('ent.Zone.getVillage', mz)
    fb.op('JNull', reg=mv, offset='an_e')  # no village: not counted by updateOwner
    fb.op('Add', dst=miss, a=miss, b=one_f)
    fb.op('JNull', reg=mo, offset='an_nown')
    fb.op('Mul', dst=con, a=con, b=den)
    fb.label('an_nown')
    # an at-war stack at (or heading to) the missing village: chance x DD_ENEMY, counts twice in the focus measure
    mvt = fb.reg(cx.t('ent.Entity'))
    fb.op('Mov', dst=mvt, src=mv)
    _unreach(fb, b, cx, mvt, now, 'an_d', 1)  # a missing village out of supply reach: the ring adds nothing (user: no
    # deep desert at all costs; Fremen cycled on Alifgah across the desert instead of expanding)
    fb.op('Call3', dst=hthr, fun=threat, arg0=fac, arg1=mvt, arg2=local_r)
    fb.op('JSLte', a=hthr, b=zero, offset='an_ncon')
    fb.op('Mul', dst=con, a=con, b=den)
    fb.op('Add', dst=mx2, a=mx2, b=one_f)
    fb.label('an_ncon')
    # within DD_BASE_R of another faction's main base
    fb.op('JNull', reg=facs, offset='an_e')
    fb.op('Mov', dst=k3, src=zi)
    b.loop_head('an_f')
    fb.op('JSGte', a=k3, b=b.field(facs, 'length'), offset='an_e')
    of = b.cast(b.call('hl.types.ArrayObj.getDyn', facs, k3), 'ent.Faction')
    fb.op('Incr', dst=k3)
    fb.op('JNull', reg=of, offset='an_f')
    fb.op('JEq', a=of, b=fac, offset='an_f')
    mbs = b.field(of, 'mainBases')
    fb.op('JNull', reg=mbs, offset='an_f')
    fb.op('Mov', dst=k4, src=zi)
    b.loop_head('an_g')
    fb.op('JSGte', a=k4, b=b.field(mbs, 'length'), offset='an_f')
    mb = b.cast(b.call('hl.types.ArrayObj.getDyn', mbs, k4), 'ent.Entity')
    fb.op('Incr', dst=k4)
    fb.op('JNull', reg=mb, offset='an_g')
    mve = fb.reg(cx.t('ent.Entity'))
    fb.op('Mov', dst=mve, src=mv)
    fb.op('JSGt', a=b.call('ent.Entity.getDistTo', mve, mb), b=b.const('f64', DD_BASE_R), offset='an_g')
    fb.op('Mul', dst=con, a=con, b=den)
    fb.op('Add', dst=mx2, a=mx2, b=one_f)  # counts twice in the focus measure (an_hok)
    fb.op('JAlways', offset='an_e')  # once per missing neighbour
    fb.label('an_ed')
    fb.op('Add', dst=miss, a=miss, b=one_f)
    # the candidate's own extras, as the focus measure counts them for every missing village (the loop above skips
    # its zone): an at-war stack at it, and within DD_BASE_R of another faction's main base (once)
    fb.op('Call3', dst=hthr, fun=threat, arg0=fac, arg1=se, arg2=local_r)
    fb.op('JSLte', a=hthr, b=zero, offset='an_scn')
    fb.op('Add', dst=mx2, a=mx2, b=one_f)
    fb.label('an_scn')
    fb.op('JNull', reg=facs, offset='an_sbd')
    fb.op('Mov', dst=k3, src=zi)
    b.loop_head('an_sf')
    fb.op('JSGte', a=k3, b=b.field(facs, 'length'), offset='an_sbd')
    sof = b.cast(b.call('hl.types.ArrayObj.getDyn', facs, k3), 'ent.Faction')
    fb.op('Incr', dst=k3)
    fb.op('JNull', reg=sof, offset='an_sf')
    fb.op('JEq', a=sof, b=fac, offset='an_sf')
    smbs = b.field(sof, 'mainBases')
    fb.op('JNull', reg=smbs, offset='an_sf')
    fb.op('Mov', dst=k4, src=zi)
    b.loop_head('an_sg')
    fb.op('JSGte', a=k4, b=b.field(smbs, 'length'), offset='an_sf')
    smb = b.cast(b.call('hl.types.ArrayObj.getDyn', smbs, k4), 'ent.Entity')
    fb.op('Incr', dst=k4)
    fb.op('JNull', reg=smb, offset='an_sg')
    fb.op('JSGt', a=b.call('ent.Entity.getDistTo', se, smb), b=b.const('f64', DD_BASE_R), offset='an_sg')
    fb.op('Add', dst=mx2, a=mx2, b=one_f)
    fb.label('an_sbd')
    # not the focus ring (more villages missing, or as many but more hops; the focus measure: near-base ones twice)
    fb.op('Add', dst=mx2, a=mx2, b=miss)
    hzc = fb.reg(cx.t('f64'))
    fb.op('ToSFloat', dst=hzc, src=hz)
    fb.op('Add', dst=mx2, a=mx2, b=hzc)  # the focus rank (an_hok): missing + hops
    fb.op('JSLt', a=mx2, b=mmin, offset='an_dnear')
    fb.op('JSGt', a=mx2, b=mmin, offset='an_dfar')
    fb.op('JSLte', a=hz, b=hmin, offset='an_dnear')
    fb.label('an_dfar')
    fb.op('Mul', dst=con, a=con, b=_ratio(fb, b, DD_FAR))
    fb.label('an_dnear')
    fb.op('JSLte', a=con, b=cmx, offset='an_cmx')  # best ring chance (flat bonus)
    fb.op('Mov', dst=cmx, src=con)
    fb.label('an_cmx')
    fb.op('SDiv', dst=con, a=con, b=miss)
    fb.op('Add', dst=dd, a=dd, b=con)
    fb.op('JAlways', offset='an_d')
    fb.label('an_ddx')
    # ring village (map 'dring' = now); uncontested ring in progress with < DD_TRIES launches: hold the others
    fb.op('JSLte', a=dd, b=zero, offset='an_rg')
    fb.op('Bool', dst=isr, value=True)
    b.call('haxe.ds.ObjectMap.set', dring, fb.dyn(se), fb.dyn(now))
    fb.op('JTrue', cond=hold, offset='an_rg')
    fb.op('Call2', dst=cln, fun=ddc, arg0=fac, arg1=z)
    fb.op('JFalse', cond=cln, offset='an_rg')
    trv = b.call('haxe.ds.ObjectMap.get', dtries, fb.dyn(se))
    fb.op('JNull', reg=trv, offset='an_rgh')
    fb.op('SafeCast', dst=trq, src=trv)
    fb.op('JSGte', a=trq, b=b.const('f64', DD_TRIES), offset='an_rg')
    fb.label('an_rgh')
    fb.op('Bool', dst=hold, value=True)
    fb.label('an_rg')
    # reachable over land: the candidate borders one of our zones that isn't deep desert
    fb.op('JSLte', a=dd, b=zero, offset='an_lk')
    fb.op('Mov', dst=k1, src=zi)
    b.loop_head('an_l')
    fb.op('JSGte', a=k1, b=b.field(zn, 'length'), offset='an_unl')
    lz = b.cast(b.call('hl.types.ArrayObj.getDyn', zn, k1), 'ent.Zone')
    fb.op('Incr', dst=k1)
    fb.op('JNull', reg=lz, offset='an_l')
    fb.op('JNotEq', a=b.field(lz, 'owner'), b=fac, offset='an_l')
    fb.op('JTrue', cond=b.call('ent.Zone.isDeepDesert', lz), offset='an_l')
    fb.op('JAlways', offset='an_lk')
    fb.label('an_unl')
    fb.op('Mul', dst=dd, a=dd, b=_ratio(fb, b, DD_LINK))
    fb.op('Mul', dst=cmx, a=cmx, b=_ratio(fb, b, DD_LINK))
    fb.label('an_lk')
    fb.op('JSLte', a=dd, b=b.const('f64', DD_CAP), offset='an_ddc')
    fb.op('Mov', dst=dd, src=b.const('f64', DD_CAP))
    fb.label('an_ddc')
    fb.op('Mul', dst=q, a=dd, b=ddw)
    fb.op('Add', dst=q, a=q, b=one_f)
    fb.op('Mul', dst=sc, a=sc, b=q)
    # flat ring bonus: DD_ADD x best chance x weight, per cost like the rest
    fb.op('Mul', dst=q, a=cmx, b=ddw)
    fb.op('Mul', dst=q, a=q, b=b.const('f64', DD_ADD))
    fb.op('JSLte', a=c, b=zero, offset='an_dda')
    fb.op('Mul', dst=q, a=q, b=cmin)
    fb.op('SDiv', dst=q, a=q, b=c)
    fb.label('an_dda')
    fb.op('Add', dst=sc, a=sc, b=q)
    fb.op('JSLte', a=dd, b=zero, offset='an_dd')
    fb.op('Call2', dst=feas, fun=ddc, arg0=fac, arg1=z)
    fb.op('JFalse', cond=feas, offset='an_dd')
    fb.op('JSGte', a=cf, b=one_f, offset='an_dd')
    fb.op('Mov', dst=cf, src=one_f)
    fb.label('an_dd')
    fb.op('Mul', dst=sc, a=sc, b=cf)
    # contact tension (AI-POLICY §5c step 2): x (1 + T) for a village within TEN_R of ours that has rubbed
    fb.op('Call2', dst=q, fun=helpers['tension'], arg0=fac, arg1=se)
    fb.op('Add', dst=q, a=q, b=one_f)
    fb.op('Mul', dst=sc, a=sc, b=q)
    floor = _ratio(fb, b, ANNEX_FLOOR)
    fb.op('JSGte', a=sc, b=floor, offset='an_fl')
    fb.op('Mov', dst=sc, src=floor)
    fb.label('an_fl')
    b.call('haxe.ds.ObjectMap.set', res, fb.dyn(se), fb.dyn(sc))
    fb.op('JFalse', cond=logc, offset='an_nolc')
    _log_ev(fb, b, cx, helpers, 'acand', [('f', fb.get(fac, 'kind')), ('tgt', se), ('v0', vo), ('hops', hz2),
                                          ('sp', spb), ('cf%', cf), ('cen%', cenf), ('dd%', dd), ('c', c),
                                          ('cmin', cmin), ('s', sc), ('n', n)])
    fb.label('an_nolc')
    fb.op('JFalse', cond=isr, offset='an_br')
    fb.op('JSLte', a=sc, b=brs, offset='an_br')
    fb.op('Mov', dst=brs, src=sc)
    fb.op('Mov', dst=brc, src=c)
    fb.op('Mov', dst=brdd, src=dd)
    fb.op('Mov', dst=brest, src=se)
    fb.label('an_br')
    fb.op('JSLte', a=sc, b=bs, offset='an2')
    fb.op('Mov', dst=bs, src=sc)
    fb.op('Mov', dst=bc, src=c)
    fb.op('Mov', dst=bdd, src=dd)
    fb.op('Mov', dst=best, src=se)
    fb.op('JAlways', offset='an2')
    fb.label('an2d')
    # lone candidate: past the opening (we own > EARLY_VILLAGES structures), vanilla's only candidate is taken only
    # if it adds something (ring / special region / spice); else dropped: no Annex now, the armies stay free and
    # the supply range grows (Fremen annexed Ur-Al'nun, 181 from Tabr, the sole candidate, 30 s before ring
    # villages entered range)
    fb.op('JNotEq', a=n, b=b.const('i32', 1), offset='an_lone')
    # only while a deep-desert ring is open for us (the case it was made for); others take their only candidate:
    # waiting for the range to grow never ends when only an Annex grows it (Harkonnen x6, Smugglers x5 in 9 min)
    fb.op('JSLte', a=ddw, b=zero, offset='an_lone')
    fb.op('JSGte', a=hmin, b=b.const('i32', 999), offset='an_lone')
    fb.op('JSLte', a=mn, b=b.const('i32', EARLY_VILLAGES), offset='an_lone')
    fb.op('JNull', reg=best, offset='an_lone')
    fb.op('JSGt', a=bdd, b=zero, offset='an_lone')
    fb.op('Call2', dst=q, fun=helpers['tension'], arg0=fac, arg1=best)
    fb.op('JSGt', a=q, b=zero, offset='an_lone')  # a contact village is never 'plain'
    fb.op('JEq', a=fb.dyn(best), b=b.call('haxe.ds.ObjectMap.get', _global_map(fb, b, cx, 'spv'), fb.dyn(fac)),
          offset='an_lone')  # the director's pressed village stands
    lz = b.call('ent.Entity.get_zone', best)
    fb.op('JNull', reg=lz, offset='an_lone')
    fb.op('JTrue', cond=b.call('ent.Zone.hasSpice', lz), offset='an_lone')
    law = fb.get(lz, 'inf', 'props', 'aiWeight')
    fb.op('JNull', reg=law, offset='an_lnx')
    fb.op('SafeCast', dst=aw, src=law)
    fb.op('JSGte', a=aw, b=b.const('f64', 20), offset='an_lone')
    fb.label('an_lnx')
    b.call('haxe.ds.ObjectMap.remove', res, fb.dyn(best))
    b.call('haxe.ds.ObjectMap.set', _global_map(fb, b, cx, 'alonev'), fb.dyn(best),
           fb.dyn(b.field(_state(fb, b, cx), 'time')))  # raid leaves it alone (rules/raid.py)
    _throttle(fb, b, cx, 'alone', fac, ASCORE_T, 'end')
    _log_ev(fb, b, cx, helpers, 'alone', [('f', fb.get(fac, 'kind')), ('tgt', best), ('s', bs), ('c', bc)])
    fb.op('JAlways', offset='end')
    fb.label('an_lone')
    # ring hold: also while one of our armies runs an Annex order on an uncontested ring village (it isn't a
    # candidate then)
    fb.op('JSLte', a=ddw, b=zero, offset='an_h3')
    fb.op('JTrue', cond=hold, offset='an_hold')
    arms, an = _my_armies(fb, b, fac, 'an_h3')
    ar = _army_loop(fb, b, arms, an, j, 'an_o', 'an_h3')
    ao = fb.reg(cx.t('logic.ai.AIOrder'))
    _order_of(fb, b, cx, fac, ar, ao, 'an_o')  # its live order (Unit.aiOrder is never maintained)
    att = b.field(ao, 'targetType')
    fb.op('JNull', reg=att, offset='an_o')
    aix = fb.reg(cx.t('i32'))
    fb.op('EnumIndex', dst=aix, value=att)
    fb.op('JNotEq', a=aix, b=b.const('i32', T_STRUCT), offset='an_o')
    asa = b.cast(fb.get(ao, 'siegeAction'), 'String')
    fb.op('JNull', reg=asa, offset='an_o')
    fb.op('JNotEq', a=b.call('String.__compare', asa, fb.dyn(annex)), b=zi, offset='an_o')
    atg = fb.reg(cx.t('ent.Entity'))
    fb.op('Mov', dst=atg, src=b.cast(b.call('logic.ai.AIOrder.getTarget', ao), 'ent.Entity'))
    fb.op('JNull', reg=atg, offset='an_o')
    atz = b.call('ent.Entity.get_zone', atg)
    fb.op('JNull', reg=atz, offset='an_o')
    fb.op('JEq', a=b.field(atz, 'owner'), b=fac, offset='an_o')
    fb.op('Call2', dst=cln, fun=ddc, arg0=fac, arg1=atz)
    fb.op('JFalse', cond=cln, offset='an_o')
    atv = b.call('haxe.ds.ObjectMap.get', dtries, fb.dyn(atg))
    fb.op('JNull', reg=atv, offset='an_hold')
    fb.op('SafeCast', dst=trq, src=atv)
    fb.op('JSGte', a=trq, b=b.const('f64', DD_TRIES), offset='an_o')
    fb.label('an_hold')
    prs = b.call('haxe.ds.ObjectMap.get', _global_map(fb, b, cx, 'spv'), fb.dyn(fac))  # strat's pressed village
    fb.op('Mov', dst=i, src=zi)
    b.loop_head('an3')
    fb.op('JSGte', a=i, b=n, offset='an3d')
    s3 = b.cast(b.call('hl.types.ArrayObj.getDyn', 0, i), 'ent.Structure')
    fb.op('Incr', dst=i)
    fb.op('JNull', reg=s3, offset='an3')
    fb.op('Mov', dst=se, src=s3)
    fb.op('JNull', reg=b.call('haxe.ds.ObjectMap.get', res, fb.dyn(se)), offset='an3')
    fb.op('JEq', a=fb.dyn(se), b=prs, offset='an3')  # pressed in annex mode: the director's call stands
    rv = b.call('haxe.ds.ObjectMap.get', dring, fb.dyn(se))
    fb.op('JNull', reg=rv, offset='an3x')
    fb.op('SafeCast', dst=q, src=rv)
    fb.op('JEq', a=q, b=now, offset='an3')  # a ring village in this call: kept
    fb.label('an3x')
    b.call('haxe.ds.ObjectMap.remove', res, fb.dyn(se))
    fb.op('Incr', dst=nh)
    fb.op('JAlways', offset='an3')
    fb.label('an3d')
    fb.op('Mov', dst=best, src=brest)
    fb.op('Mov', dst=bs, src=brs)
    fb.op('Mov', dst=bc, src=brc)
    fb.op('Mov', dst=bdd, src=brdd)
    fb.label('an_h3')
    # top 3: the best is unaffordable now (vanilla reserves Authority and waits on it; our retry block then walks the
    # list one pick at a time) and the 2nd or 3rd is affordable -> the unaffordable ones above it drop just below it
    # (Harkonnen: Aynnah MissingResources, Gun-ur retried, then the Liberation gauge sent 9 armies across the map)
    t1, t2, t3 = (fb.reg(cx.t('ent.Entity')) for _ in range(3))
    s1, s2, s3 = (fb.reg(cx.t('f64')) for _ in range(3))
    for tr in (t1, t2, t3):
        fb.op('Null', dst=tr)
    for sr in (s1, s2, s3):
        fb.op('Mov', dst=sr, src=zero)
    fb.op('Mov', dst=i, src=zi)
    b.loop_head('tp')
    fb.op('JSGte', a=i, b=n, offset='tpd')
    s4 = b.cast(b.call('hl.types.ArrayObj.getDyn', 0, i), 'ent.Structure')
    fb.op('Incr', dst=i)
    fb.op('JNull', reg=s4, offset='tp')
    fb.op('Mov', dst=se, src=s4)
    tv = b.call('haxe.ds.ObjectMap.get', res, fb.dyn(se))
    fb.op('JNull', reg=tv, offset='tp')
    fb.op('SafeCast', dst=q, src=tv)
    fb.op('JSLte', a=q, b=s3, offset='tp')
    fb.op('Mov', dst=s3, src=q)
    fb.op('Mov', dst=t3, src=se)
    fb.op('JSLte', a=s3, b=s2, offset='tp')  # bubble up
    for (ta, sa), (tb_, sb) in (((t2, s2), (t3, s3)), ((t1, s1), (t2, s2))):
        fb.op('Mov', dst=q, src=sa)
        fb.op('Mov', dst=sa, src=sb)
        fb.op('Mov', dst=sb, src=q)
        tmp = fb.reg(cx.t('ent.Entity'))
        fb.op('Mov', dst=tmp, src=ta)
        fb.op('Mov', dst=ta, src=tb_)
        fb.op('Mov', dst=tb_, src=tmp)
        if ta is t2:
            fb.op('JSLte', a=s2, b=s1, offset='tp')
    fb.op('JAlways', offset='tp')
    fb.label('tpd')
    ctl = b.field(fac, 'aiController')
    fb.op('JNull', reg=ctl, offset='an_lgb0')
    aff = fb.reg(cx.t('bool'))
    prio3 = fb.dyn(b.const('i32', 3))

    def affordable(st, lbl_no):
        """Fall through when st's Annex cost is affordable now, else jump to lbl_no."""
        sg = b.field(b.cast(fb.dyn(st), 'ent.Structure'), 'siege')
        fb.op('JNull', reg=sg, offset=lbl_no)
        arr = fb.reg(cx.code.types[oc.type.value].definition.ret.value)
        fb.op('Call4', dst=arr, fun=oc.findex.value, arg0=sg, arg1=annex, arg2=onull, arg3=fac)
        fb.op('JNull', reg=arr, offset=lbl_no)
        miss = b.call('logic.ai.AIController.getMissingResources', ctl, arr, prio3)
        ok_ = _uid('afy')
        fb.op('JNull', reg=miss, offset=ok_)
        fb.op('JSGt', a=b.field(miss, 'length'), b=zi, offset=lbl_no)
        fb.label(ok_)

    fb.op('JNull', reg=t1, offset='an_lgb0')
    fb.op('JNull', reg=t2, offset='an_lgb0')
    prs2 = b.call('haxe.ds.ObjectMap.get', _global_map(fb, b, cx, 'spv'), fb.dyn(fac))
    fb.op('JEq', a=fb.dyn(t1), b=prs2, offset='an_lgb0')  # the director's pressed village stands
    aswt = _global_map(fb, b, cx, 'aswt')  # faction -> since when the best is unaffordable
    affordable(t1, 'af1no')
    b.call('haxe.ds.ObjectMap.remove', aswt, fb.dyn(fac))
    fb.op('JAlways', offset='an_lgb0')  # the best is affordable: vanilla takes it
    fb.label('af1no')
    fb.op('JNotNull', reg=b.call('haxe.ds.ObjectMap.get', aswt, fb.dyn(fac)), offset='aswt_ok')
    b.call('haxe.ds.ObjectMap.set', aswt, fb.dyn(fac), fb.dyn(now))
    fb.label('aswt_ok')
    pick, ps_ = fb.reg(cx.t('ent.Entity')), fb.reg(cx.t('f64'))
    fb.op('Mov', dst=pick, src=t2)
    fb.op('Mov', dst=ps_, src=s2)
    affordable(t2, 'af2no')
    fb.op('JAlways', offset='afswap')
    fb.label('af2no')
    fb.op('JNull', reg=t3, offset='an_lgb0')
    fb.op('Mov', dst=pick, src=t3)
    fb.op('Mov', dst=ps_, src=s3)
    affordable(t3, 'af3no')
    # t2 unaffordable and above t3: below t3 too
    fb.op('Mul', dst=q, a=ps_, b=_ratio(fb, b, 0.98))
    b.call('haxe.ds.ObjectMap.set', res, fb.dyn(t2), fb.dyn(q))
    fb.label('afswap')
    fb.op('Mul', dst=q, a=ps_, b=_ratio(fb, b, 0.99))
    b.call('haxe.ds.ObjectMap.set', res, fb.dyn(t1), fb.dyn(q))
    _throttle(fb, b, cx, 'aswap', fac, ASCORE_T, 'an_lgb0')
    _log_ev(fb, b, cx, helpers, 'aswap', [('f', fb.get(fac, 'kind')), ('from', t1), ('to', pick), ('s', ps_)])
    fb.op('JAlways', offset='an_lgb0')
    # nothing affordable in the top 3 for ASWAP_WAIT s: the best affordable candidate anywhere, every (unaffordable)
    # one scored above it drops just below it (Atreides waited 28 min on Arn-lab, c 131-148, with cheaper candidates
    # at cmin 105-123 in the list; vanilla reserves Authority for its pick and launches nothing meanwhile)
    fb.label('af3no')
    wv = b.call('haxe.ds.ObjectMap.get', aswt, fb.dyn(fac))
    fb.op('JNull', reg=wv, offset='an_lgb0')
    wq = fb.reg(cx.t('f64'))
    fb.op('SafeCast', dst=wq, src=wv)
    fb.op('Sub', dst=wq, a=now, b=wq)
    fb.op('JSLt', a=wq, b=b.const('f64', ASWAP_WAIT), offset='an_lgb0')
    fb.op('Null', dst=pick)
    fb.op('Mov', dst=ps_, src=zero)
    sw = fb.reg(cx.t('ent.Entity'))
    fb.op('Mov', dst=i, src=zi)
    b.loop_head('aw4')
    fb.op('JSGte', a=i, b=n, offset='aw4d')
    s5 = b.cast(b.call('hl.types.ArrayObj.getDyn', 0, i), 'ent.Structure')
    fb.op('Incr', dst=i)
    fb.op('JNull', reg=s5, offset='aw4')
    fb.op('Mov', dst=sw, src=s5)
    wv5 = b.call('haxe.ds.ObjectMap.get', res, fb.dyn(sw))
    fb.op('JNull', reg=wv5, offset='aw4')
    fb.op('SafeCast', dst=q, src=wv5)
    fb.op('JSLte', a=q, b=ps_, offset='aw4')
    affordable(sw, 'aw4')
    fb.op('Mov', dst=pick, src=sw)
    fb.op('Mov', dst=ps_, src=q)
    fb.op('JAlways', offset='aw4')
    fb.label('aw4d')
    fb.op('JNull', reg=pick, offset='an_lgb0')
    fb.op('Mov', dst=i, src=zi)
    b.loop_head('aw5')
    fb.op('JSGte', a=i, b=n, offset='aw5d')
    s6 = b.cast(b.call('hl.types.ArrayObj.getDyn', 0, i), 'ent.Structure')
    fb.op('Incr', dst=i)
    fb.op('JNull', reg=s6, offset='aw5')
    fb.op('Mov', dst=sw, src=s6)
    fb.op('JEq', a=sw, b=pick, offset='aw5')
    wv6 = b.call('haxe.ds.ObjectMap.get', res, fb.dyn(sw))
    fb.op('JNull', reg=wv6, offset='aw5')
    fb.op('SafeCast', dst=q, src=wv6)
    fb.op('JSLt', a=q, b=ps_, offset='aw5')
    fb.op('Mul', dst=q, a=ps_, b=_ratio(fb, b, 0.98))
    b.call('haxe.ds.ObjectMap.set', res, fb.dyn(sw), fb.dyn(q))
    fb.op('JAlways', offset='aw5')
    fb.label('aw5d')
    _throttle(fb, b, cx, 'aswap', fac, ASCORE_T, 'an_lgb0')
    _log_ev(fb, b, cx, helpers, 'aswap', [('f', fb.get(fac, 'kind')), ('from', t1), ('to', pick), ('s', ps_),
                                          ('wait', wq)])
    fb.label('an_lgb0')
    fb.op('JNotNull', reg=best, offset='an_lgb')
    fb.op('JSLte', a=nh, b=zi, offset='end')  # held with no ring candidate (its Annex runs): still logged
    fb.label('an_lgb')
    _throttle(fb, b, cx, 'ascore', fac, ASCORE_T, 'end')
    vs = fb.reg(cx.t('f64'))
    fb.op('Mov', dst=vs, src=zero)
    fb.op('JNull', reg=vb, offset='an_lg')
    vv = b.call('haxe.ds.ObjectMap.get', res, fb.dyn(vb))
    fb.op('JNull', reg=vv, offset='an_lg')
    fb.op('SafeCast', dst=vs, src=vv)
    fb.label('an_lg')
    fb.op('JSLt', a=cmin, b=big, offset='an_cm')
    fb.op('Mov', dst=cmin, src=zero)
    fb.label('an_cm')
    _log_ev(fb, b, cx, helpers, 'ascore', [('f', fb.get(fac, 'kind')), ('tgt', best), ('s', bs), ('c', bc),
                                           ('cmin', cmin), ('vb', vb), ('v0', v0), ('vs', vs), ('n', n),
                                           ('dd%', bdd), ('hold', nh), ('rt', brest), ('rs', brs),
                                           ('rdd%', brdd), ('ddh', hmin), ('ddr', mmin)])


def build_scoring(cx, new_ids, helpers):
    """Target scores: the single tryAction -> $HScoring.structures(structures, faction, k, ...) call (target
    scores for Annex / Liberate / Pillage / ...) -> wrapper:
    - retry: a structure vanilla launched a siege on less than its block ago is dropped (RETRY, doubled up to
      RETRY_MAX per relaunch right after the block ran out: a launch that keeps failing at once backs off). While its order runs vanilla
      doesn't re-pick it, so a re-pick means that order ended at once: fillAttackSteps cancels in Waiting with
      InsufficientSupply (the lowest army supply < AIOrders.estimateSupplyCost of the path) and the gauge, still
      full, re-picked the same village every ~2.5 s (Fremen Pelmah x39). Logs `space` why retry (10 s throttle);
    - stuck: FAIL_N launches on it within FAIL_WIN that created no order while an army of ours was free to go (map
      `afu` blocked-until, set by the launch wrapper) -> dropped for FAIL_BLOCK..FAIL_MAX s, logs `space` why stuck;
    - next Annex choices (map `akeep`, rules/raid.py annex-keep: top RAID_KEEP within AKEEP_T): no Pillage target;
    - DMZ (rules/dmz.py, aimod_dmzv): Pillage drops a DMZ village, its Annex / Liberate score x DMZ_W;
    - bunker preference: a positive score x BUNKER_W when the structure is within COVER_R of one of our structures
      on our land (their turrets cover each other) or within BUNKER_R of our main base.
    Original scores on any error."""
    orig = cx.fn('logic.ai.$HScoring.structures')
    ft = cx.code.types[orig.type.value].definition
    args = [a.value for a in ft.args]
    fb = FB(cx, args, ft.ret.value, fun_type=orig.type.value)
    b = B(fb)
    res = fb.reg(ft.ret.value)
    fb.op('CallN', dst=res, fun=orig.findex.value, args=list(range(len(args))))
    guard = fb.try_()
    fb.op('JNull', reg=res, offset='end')
    fb.op('JNull', reg=0, offset='end')
    fb.op('JNull', reg=1, offset='end')
    n = b.field(0, 'length')
    # press (rules/strat.py): the gates are opened for the pressed village's owner only; among its villages only the
    # pressed one stays; its Annex score x PRESS_W in annex mode (vanilla picks at random among the top scores), and
    # it is no Annex target in pillage mode (`raid` takes it)
    pvd = b.call('haxe.ds.ObjectMap.get', _global_map(fb, b, cx, 'spv'), fb.dyn(1))
    fb.op('JNull', reg=pvd, offset='nopress')
    pfp = b.cast(b.call('haxe.ds.ObjectMap.get', _global_map(fb, b, cx, 'spf'), fb.dyn(1)), 'ent.Faction')
    fb.op('JNull', reg=pfp, offset='nopress')
    pab, isann = fb.reg(cx.t('bool')), fb.reg(cx.t('bool'))
    fb.op('SafeCast', dst=pab, src=b.call('haxe.ds.ObjectMap.get', _global_map(fb, b, cx, 'spa'), fb.dyn(1)))
    fb.op('Bool', dst=isann, value=True)
    fb.op('JEq', a=b.call('String.__compare', 2, fb.dyn(fb.string('Annex'))), b=b.const('i32', 0), offset='pk')
    fb.op('Bool', dst=isann, value=False)
    fb.label('pk')
    pi = fb.reg(cx.t('i32'))
    psc = fb.reg(cx.t('f64'))
    pse = fb.reg(cx.t('ent.Entity'))
    fb.op('Mov', dst=pi, src=b.const('i32', 0))
    b.loop_head('ps')
    fb.op('JSGte', a=pi, b=n, offset='nopress')
    pst = b.cast(b.call('hl.types.ArrayObj.getDyn', 0, pi), 'ent.Structure')
    fb.op('Incr', dst=pi)
    fb.op('JNull', reg=pst, offset='ps')
    fb.op('Mov', dst=pse, src=pst)
    fb.op('JNotEq', a=b.call('ent.Entity.get_owner', pse), b=pfp, offset='ps')
    fb.op('JNotEq', a=fb.dyn(pse), b=pvd, offset='pdrop')
    fb.op('JFalse', cond=isann, offset='ps')  # the pressed village: other actions (Pillage, ...) unchanged
    fb.op('JFalse', cond=pab, offset='pdrop')  # pillage mode: not an Annex target (no Authority reserved for it)
    pv0 = b.call('haxe.ds.ObjectMap.get', res, fb.dyn(pse))
    fb.op('JNull', reg=pv0, offset='ps')
    fb.op('SafeCast', dst=psc, src=pv0)
    fb.op('Mul', dst=psc, a=psc, b=b.const('f64', PRESS_W))
    b.call('haxe.ds.ObjectMap.set', res, fb.dyn(pse), fb.dyn(psc))
    fb.op('JAlways', offset='ps')
    fb.label('pdrop')
    b.call('haxe.ds.ObjectMap.remove', res, fb.dyn(pse))
    fb.op('JAlways', offset='ps')
    fb.label('nopress')
    # tension lift (strat_levers): an at-war owner vanilla doesn't target (desiredStatus 0) keeps only the villages
    # that are our contact partners at TEN_GATE (Smugglers' Shariyah / Atreides' Hadnin 113 apart, at war, T at the
    # cap: neither ever listed the other's village)
    dipf = b.field(b.field(1, 'aiController'), 'diplomacy')
    fb.op('JNull', reg=dipf, offset='tgdone')
    tst = _state(fb, b, cx)
    tpf = b.call('haxe.ds.ObjectMap.get', _global_map(fb, b, cx, 'spf'), fb.dyn(1))
    gi, gds = fb.reg(cx.t('i32')), fb.reg(cx.t('i32'))
    gq = fb.reg(cx.t('f64'))
    gse = fb.reg(cx.t('ent.Entity'))
    fb.op('Mov', dst=gi, src=b.const('i32', 0))
    b.loop_head('tg')
    fb.op('JSGte', a=gi, b=n, offset='tgdone')
    gst = b.cast(b.call('hl.types.ArrayObj.getDyn', 0, gi), 'ent.Structure')
    fb.op('Incr', dst=gi)
    fb.op('JNull', reg=gst, offset='tg')
    fb.op('Mov', dst=gse, src=gst)
    go = b.call('ent.Entity.get_owner', gse)
    fb.op('JNull', reg=go, offset='tg')
    fb.op('JEq', a=go, b=1, offset='tg')
    fb.op('JEq', a=fb.dyn(go), b=tpf, offset='tg')  # the press owner: handled above
    fb.op('JFalse', cond=b.call('logic.state.State.areAtWar', tst, 1, go), offset='tg')
    fb.op('Int', dst=gds, ptr=cx.code.add_i32(1).value)
    gg = fb.try_()  # throws for a faction the diplomacy module doesn't track
    fb.op('Mov', dst=gds, src=b.call('logic.ai.Diplomacy.getTargetStatus', dipf, go))
    fb.end_try(gg)
    fb.op('JSGte', a=gds, b=b.const('i32', 1), offset='tg')  # vanilla targets it anyway
    fb.op('Call2', dst=gq, fun=helpers['tension'], arg0=1, arg1=gse)
    fb.op('JSGte', a=gq, b=_ratio(fb, b, TEN_GATE), offset='tg')
    tdk = fb.reg(cx.t('bool'))  # a DMZ village (its owner listed for the DMZ): kept, the DMZ step below decides
    fb.op('Call2', dst=tdk, fun=helpers['dmzv'], arg0=1, arg1=gst)
    fb.op('JTrue', cond=tdk, offset='tg')
    b.call('haxe.ds.ObjectMap.remove', res, fb.dyn(gse))
    fb.op('JAlways', offset='tg')
    fb.label('tgdone')
    # our next Annex choices (map `akeep` faction -> village -> time, rules/raid.py annex-keep: top RAID_KEEP within
    # AKEEP_T) are no Pillage targets: vanilla's gauge pillaged Smugglers' top choice (Arslulah x3, Ya-lab), Devastating it and doubling
    # our Annex cost there
    fb.op('JNotEq', a=b.call('String.__compare', 2, fb.dyn(fb.string('Pillage'))), b=b.const('i32', 0),
          offset='akdone')
    akv = _fac_map(fb, b, cx, 'akeep', 1)
    ai_, aq, ase = fb.reg(cx.t('i32')), fb.reg(cx.t('f64')), fb.reg(cx.t('ent.Entity'))
    anow = b.field(_state(fb, b, cx), 'time')
    fb.op('Mov', dst=ai_, src=b.const('i32', 0))
    b.loop_head('akl')
    fb.op('JSGte', a=ai_, b=n, offset='akdone')
    ast_ = b.cast(b.call('hl.types.ArrayObj.getDyn', 0, ai_), 'ent.Structure')
    fb.op('Incr', dst=ai_)
    fb.op('JNull', reg=ast_, offset='akl')
    fb.op('Mov', dst=ase, src=ast_)
    # a village of an uncontested deep-desert ring in progress (aimod_ddclean, as raid / the pillage press): no
    # Pillage target either (Fremen's gauge pillaged neutral Alifdad, the village closing their ring, 44:57)
    pdz = b.call('ent.Entity.get_zone', ase)
    fb.op('JNull', reg=pdz, offset='akk')
    pdc = fb.reg(cx.t('bool'))
    fb.op('Call2', dst=pdc, fun=helpers['ddclean'], arg0=1, arg1=pdz)
    fb.op('JFalse', cond=pdc, offset='akk')
    b.call('haxe.ds.ObjectMap.remove', res, fb.dyn(ase))
    _throttle(fb, b, cx, 'pkeep', ase, 60, 'akl')
    _log_ev(fb, b, cx, helpers, 'pkeep', [('f', fb.get(1, 'kind')), ('v', ase)])
    fb.op('JAlways', offset='akl')
    fb.label('akk')
    akt = b.call('haxe.ds.ObjectMap.get', akv, fb.dyn(ase))
    fb.op('JNull', reg=akt, offset='akl')
    fb.op('SafeCast', dst=aq, src=akt)
    fb.op('Sub', dst=aq, a=anow, b=aq)
    fb.op('JSGte', a=aq, b=b.const('f64', AKEEP_T), offset='akl')
    b.call('haxe.ds.ObjectMap.remove', res, fb.dyn(ase))
    fb.op('JAlways', offset='akl')
    fb.label('akdone')
    # DMZ (rules/dmz.py): a border village of an at-war neighbour holding >= DMZ_WAR of them is taken, not burnt:
    # no Pillage target; its Annex / Liberate score x DMZ_W
    dmode = fb.reg(cx.t('i32'))  # 0 other, 1 pillage, 2 annex / liberate
    fb.op('Int', dst=dmode, ptr=cx.code.add_i32(1).value)
    fb.op('JEq', a=b.call('String.__compare', 2, fb.dyn(fb.string('Pillage'))), b=b.const('i32', 0), offset='dmk')
    fb.op('Int', dst=dmode, ptr=cx.code.add_i32(2).value)
    fb.op('JEq', a=b.call('String.__compare', 2, fb.dyn(fb.string('Annex'))), b=b.const('i32', 0), offset='dmk')
    fb.op('JEq', a=b.call('String.__compare', 2, fb.dyn(fb.string('Liberate'))), b=b.const('i32', 0), offset='dmk')
    fb.op('JAlways', offset='dmdone')
    fb.label('dmk')
    di = fb.reg(cx.t('i32'))
    dok = fb.reg(cx.t('bool'))
    dsc = fb.reg(cx.t('f64'))
    dse = fb.reg(cx.t('ent.Entity'))
    fb.op('Mov', dst=di, src=b.const('i32', 0))
    b.loop_head('dml')
    fb.op('JSGte', a=di, b=n, offset='dmdone')
    dst_ = b.cast(b.call('hl.types.ArrayObj.getDyn', 0, di), 'ent.Structure')
    fb.op('Incr', dst=di)
    fb.op('JNull', reg=dst_, offset='dml')
    fb.op('Call2', dst=dok, fun=helpers['dmzv'], arg0=1, arg1=dst_)
    fb.op('JFalse', cond=dok, offset='dml')
    fb.op('Mov', dst=dse, src=dst_)
    fb.op('JNotEq', a=dmode, b=b.const('i32', 1), offset='dmw')
    b.call('haxe.ds.ObjectMap.remove', res, fb.dyn(dse))
    fb.op('JAlways', offset='dml')
    fb.label('dmw')
    dv0 = b.call('haxe.ds.ObjectMap.get', res, fb.dyn(dse))
    fb.op('JNull', reg=dv0, offset='dml')
    fb.op('SafeCast', dst=dsc, src=dv0)
    fb.op('JSLte', a=dsc, b=b.const('f64', 0), offset='dml')
    fb.op('Mul', dst=dsc, a=dsc, b=_ratio(fb, b, DMZ_W))
    b.call('haxe.ds.ObjectMap.set', res, fb.dyn(dse), fb.dyn(dsc))
    fb.op('JAlways', offset='dml')
    fb.label('dmdone')
    mine = b.cast(fb.get(1, 'structures', 'array'), 'hl.types.ArrayObj')
    fb.op('JNull', reg=mine, offset='end')
    mn = b.field(mine, 'length')
    # first spice: an Annex while we own no spice village, faction not SPICE_ANY (they harvest anywhere): its spice
    # villages are never dropped as `stuck` (spice1, per candidate below)
    needsp, spice1 = fb.reg(cx.t('bool')), fb.reg(cx.t('bool'))
    fb.op('Bool', dst=needsp, value=False)
    spd = _uid('spd')
    fb.op('JNotEq', a=b.call('String.__compare', 2, fb.dyn(fb.string('Annex'))), b=b.const('i32', 0), offset=spd)
    skd = b.field(1, 'kind')
    fb.op('JNull', reg=skd, offset=spd)
    for nm in SPICE_ANY:
        fb.op('JEq', a=b.call('String.__compare', skd, fb.dyn(fb.string(nm))), b=b.const('i32', 0), offset=spd)
    snd = fb.get(1, 'cacheData', 'numSpiceVillages')
    fb.op('JNull', reg=snd, offset=spd)
    snp = fb.reg(cx.t('i32'))
    fb.op('SafeCast', dst=snp, src=snd)
    fb.op('JSGt', a=snp, b=b.const('i32', 0), offset=spd)
    fb.op('Bool', dst=needsp, value=True)
    fb.label(spd)
    i, j = fb.reg(cx.t('i32')), fb.reg(cx.t('i32'))
    fb.op('Mov', dst=i, src=b.const('i32', 0))
    zero = b.const('f64', 0)
    cover, br, w = b.const('f64', COVER_R), b.const('f64', BUNKER_R), _ratio(fb, b, BUNKER_W)
    sc, r = fb.reg(cx.t('f64')), fb.reg(cx.t('f64'))
    se, te = fb.reg(cx.t('ent.Entity')), fb.reg(cx.t('ent.Entity'))
    now = b.field(_state(fb, b, cx), 'time')
    b.loop_head('s')
    fb.op('JSGte', a=i, b=n, offset='annex')
    s = b.cast(b.call('hl.types.ArrayObj.getDyn', 0, i), 'ent.Structure')
    fb.op('Incr', dst=i)
    fb.op('JNull', reg=s, offset='s')
    fb.op('Mov', dst=se, src=s)
    v = b.call('haxe.ds.ObjectMap.get', res, fb.dyn(se))
    fb.op('JNull', reg=v, offset='s')
    _recent_launch(fb, b, cx, se, now, 'retry', fac=1, helpers=helpers)
    fb.op('Bool', dst=spice1, value=False)
    fb.op('JFalse', cond=needsp, offset='sp1d')
    # neutral only: after a late-game loss the priority returns (vanilla +100, ANNEX_SPICE1), but a spice village held
    # by a strong owner keeps the stuck backoff (no endless re-pick of a target we can't take)
    fb.op('JNotNull', reg=b.call('ent.Entity.get_owner', se), offset='sp1d')
    spz = b.call('ent.Entity.get_zone', se)
    fb.op('JNull', reg=spz, offset='sp1d')
    fb.op('Mov', dst=spice1, src=b.call('ent.Zone.hasSpice', spz))
    fb.label('sp1d')
    # stuck: launches here kept ending without an order (map `afu` = blocked until)
    afu = b.call('haxe.ds.ObjectMap.get', _global_map(fb, b, cx, 'afu'), fb.dyn(se))
    fb.op('JNull', reg=afu, offset='nstk')
    fb.op('SafeCast', dst=r, src=afu)
    fb.op('JSGte', a=now, b=r, offset='nstk')
    # ... not on its first block for our first spice village (user: a faction that needs spice just takes it;
    # SPICE_ANY harvest anywhere). A block that came back (map `afb` doubled past FAIL_BLOCK: it failed again right
    # after) is a real loop (a raider band we can't beat sits there): the backoff applies
    fb.op('JFalse', cond=spice1, offset='stuck')
    afbv = b.call('haxe.ds.ObjectMap.get', _global_map(fb, b, cx, 'afb'), fb.dyn(se))
    fb.op('JNull', reg=afbv, offset='nstk')
    fb.op('SafeCast', dst=r, src=afbv)
    fb.op('JSLte', a=r, b=b.const('f64', FAIL_BLOCK), offset='nstk')
    fb.op('JAlways', offset='stuck')
    fb.label('nstk')
    fb.op('SafeCast', dst=sc, src=v)
    fb.op('JSLte', a=sc, b=zero, offset='s')
    fb.op('Mov', dst=j, src=b.const('i32', 0))
    b.loop_head('m')
    fb.op('JSGte', a=j, b=mn, offset='s')
    t = b.cast(b.call('hl.types.ArrayObj.getDyn', mine, j), 'ent.Structure')
    fb.op('Incr', dst=j)
    fb.op('JNull', reg=t, offset='m')
    fb.op('Mov', dst=te, src=t)
    fb.op('JEq', a=te, b=se, offset='m')
    z = b.call('ent.Entity.get_zone', te)
    fb.op('JNull', reg=z, offset='m')
    fb.op('JNotEq', a=b.field(z, 'owner'), b=1, offset='m')  # on our land (not a UWHeadquarters in theirs)
    fb.op('Mov', dst=r, src=cover)
    fb.op('JFalse', cond=b.call('ent.Structure.get_isMainBase', t), offset='rset')
    fb.op('Mov', dst=r, src=br)
    fb.label('rset')
    fb.op('JSGt', a=b.call('ent.Entity.getDistTo', se, te), b=r, offset='m')
    fb.op('Mul', dst=sc, a=sc, b=w)
    b.call('haxe.ds.ObjectMap.set', res, fb.dyn(se), fb.dyn(sc))
    fb.op('JAlways', offset='s')
    fb.label('retry')
    b.call('haxe.ds.ObjectMap.remove', res, fb.dyn(se))
    _throttle(fb, b, cx, 'space', 1, 10, 's')
    near = fb.reg(cx.t('ent.Entity'))
    fb.op('Null', dst=near)
    _log_ev(fb, b, cx, helpers, 'space', [('f', fb.get(1, 'kind')), ('k', 2), ('why', 'retry'), ('tgt', se),
                                          ('near', near)])
    fb.op('JAlways', offset='s')
    fb.label('stuck')
    b.call('haxe.ds.ObjectMap.remove', res, fb.dyn(se))
    _throttle(fb, b, cx, 'space', 1, 10, 's')
    near2 = fb.reg(cx.t('ent.Entity'))
    fb.op('Null', dst=near2)
    _log_ev(fb, b, cx, helpers, 'space', [('f', fb.get(1, 'kind')), ('k', 2), ('why', 'stuck'), ('tgt', se),
                                          ('near', near2)])
    fb.op('JAlways', offset='s')
    fb.label('annex')
    _annex_value(fb, b, cx, helpers, res, mine, mn)
    fb.label('end')
    fb.end_try(guard)
    fb.op('Ret', ret=res)
    wr = fb.build()
    new_ids.add(wr)
    helpers['scores'] = wr  # raid ranks vanilla's Annex choices with the same scores
    return {'bunker-score': _redirect(cx, 'logic.ai.$HScoring.structures', ['logic.ai.AIMilitary.tryAction'], wr)}
