"""Hunt: attack exposed at-war armies near our land and contest sieges near it (Military ArmyFight orders on an
AIEntityGroup). Start pass every START s, abort / engage pass every CHECK s."""
from rules.common import *  # noqa: F401,F403  thresholds (AI-POLICY §4) and bytecode helpers


def _log_hunt(fb, b, cx, helpers, fac, act, why, tgt, h, m, extra):
    d = fb.reg(cx.t('dynobj'))
    fb.op('New', dst=d)
    b.put(d, 'e', fb.string('hunt'))
    b.put(d, 'f', fb.get(fac, 'kind'))
    b.put(d, 'act', fb.string(act))
    if why:
        b.put(d, 'why', fb.string(why))
    tent = fb.reg(cx.t('dyn'))
    fb.op('Call1', dst=tent, fun=helpers['ent'], arg0=fb.dyn(tgt))
    b.put(d, 'tgt', tent)
    b.put(d, 'H', b.to_int(h))
    b.put(d, 'M', b.to_int(m))
    for k, r in extra.items():
        if fb.regs[r] == cx.t('ent.Entity'):
            er = fb.reg(cx.t('dyn'))
            fb.op('Call1', dst=er, fun=helpers['ent'], arg0=fb.dyn(r))
            b.put(d, k, er)
        else:
            b.put(d, k, b.to_int(r) if fb.regs[r] == cx.t('f64') else r)
    b.put(d, 'x', b.to_int(b.field(tgt, 'posx')))
    b.put(d, 'y', b.to_int(b.field(tgt, 'posy')))
    v = fb.reg(cx.t('void'))
    fb.op('Call1', dst=v, fun=helpers['log'], arg0=fb.dyn(d))


def build_hunt(cx, helpers, pw, free, threat, land, terrain, supok, short, sieged, cover, defend):
    """aimod_hunt(mil, dt): abort pass every CHECK s, start pass every START s (see module doc)."""
    fb = FB(cx, [cx.t('logic.ai.AIMilitary'), cx.t('f64')], cx.t('void'))
    b = B(fb)
    void = fb.reg(cx.t('void'))
    guard = fb.try_()
    ctrl = b.field(0, 'controller')
    fac = b.field(ctrl, 'owner')
    fb.op('JNull', reg=fac, offset='end')
    state = _state(fb, b, cx)
    t = b.field(state, 'time')
    armies = b.field(state, 'armies')
    alen = b.field(armies, 'length')
    villages = b.field(state, 'villages')
    fb.op('JNull', reg=villages, offset='end')
    vlen = b.field(villages, 'length')
    my_armies, mlen = _my_armies(fb, b, fac, 'end')
    orders_obj = b.field(ctrl, 'aiOrders')
    orders = b.field(orders_obj, 'orders')
    fb.op('JNull', reg=orders, offset='end')
    no_orders = fb.reg(cx.t('hl.types.ArrayObj'))
    fb.op('Null', dst=no_orders)
    hunt_r, local = b.const('f64', HUNT_R), b.const('f64', LOCAL)
    home_r, home_exit = b.const('f64', HOME_R), b.const('f64', HOME_EXIT)
    defend_r, leash = b.const('f64', DEFEND_R), b.const('f64', LEASH)
    contact, drift_r = b.const('f64', CONTACT), b.const('f64', DRIFT_R)
    enter, abort = _ratio(fb, b, ENTER), _ratio(fb, b, ABORT)
    sup_enter = _ratio(fb, b, SUP_ENTER)
    gather_r = b.const('f64', GATHER_R)
    kill = _ratio(fb, b, KILL)
    kill_x = _ratio(fb, b, KILL / ENTER)  # need (= ENTER x threat / terrain) x this = KILL x threat / terrain
    dfs = fb.reg(cx.t('ent.Structure'))  # our besieged structure (defensive posture), else null
    tc, tm, q, tv = (fb.reg(cx.t('f64')) for _ in range(4))  # enemy / own turret cover, scratch, scratch
    no_ent = fb.reg(cx.t('ent.Entity'))
    fb.op('Null', dst=no_ent)
    t_false, t_true = fb.reg(cx.t('bool')), fb.reg(cx.t('bool'))
    fb.op('Bool', dst=t_false, value=False)
    fb.op('Bool', dst=t_true, value=True)

    def cover_at(dst, at, exclude, own):
        fb.op('CallN', dst=dst, fun=cover, args=[fac, at, exclude, t_true if own else t_false, no_orders])
    gap = b.const('f64', HUNT_GAP)
    zero, zi, one = b.const('f64', 0), b.const('i32', 0), b.const('i32', 1)
    big = b.const('f64', 1 << 30)
    i, j, k = fb.reg(cx.t('i32')), fb.reg(cx.t('i32')), fb.reg(cx.t('i32'))
    p, h, m, need, sd, sdx, tf = (fb.reg(cx.t('f64')) for _ in range(7))
    cnt, war, vis, home = (fb.reg(cx.t('i32')) for _ in range(4))
    ok, losing = fb.reg(cx.t('bool')), fb.reg(cx.t('bool'))
    ent_r = fb.reg(cx.t('ent.Entity'))
    first = fb.reg(cx.t('ent.Entity'))
    core = fb.reg(cx.t('ent.Entity'))  # abort pass: the live member nearest our land (sd); the group is judged there
    ve, found = fb.reg(cx.t('ent.Entity')), fb.reg(cx.t('ent.Entity'))
    idx = fb.reg(cx.t('i32'))
    lastmap = _global_map(fb, b, cx, 'hunt')
    objmap = _global_map(fb, b, cx, 'hobj')

    # ---- 1. abort pass: re-check running hunts (backwards: stop() removes the order from the list)
    _tick(fb, b, cx, t, CHECK, 'new')
    fb.op('Call1', dst=dfs, fun=defend, arg0=fac)
    reason = cx.code.types[cx.fn('logic.ai.AIOrder.stop').type.value].definition.args[1].value
    cancel = fb.reg(reason)
    fb.op('MakeEnum', dst=cancel, construct=CANCEL, args=[])
    fb.op('Mov', dst=i, src=b.field(orders, 'length'))
    b.loop_head('ord')
    fb.op('JSLte', a=i, b=zi, offset='new')
    fb.op('Sub', dst=i, a=i, b=one)
    o = b.cast(b.call('hl.types.ArrayObj.getDyn', orders, i), 'logic.ai.AIOrder')
    fb.op('JNull', reg=o, offset='ord')
    fb.op('EnumIndex', dst=idx, value=b.field(o, 'type'))
    fb.op('JNotEq', a=idx, b=b.const('i32', MILITARY), offset='ord')
    tt = b.field(o, 'targetType')
    fb.op('JNull', reg=tt, offset='ord')
    fb.op('EnumIndex', dst=idx, value=tt)
    fb.op('JNotEq', a=idx, b=b.const('i32', T_GROUP), offset='ord')
    g = b.cast(b.call('logic.ai.AIOrder.getTarget', o), 'logic.ai.AIEntityGroup')
    fb.op('JNull', reg=g, offset='ab_nolog')
    fb.op('Mov', dst=ent_r, src=g)
    fb.op('Mov', dst=first, src=g)
    fb.op('Mov', dst=core, src=g)
    for r in (h, m):
        fb.op('Mov', dst=r, src=zero)
    for r in (cnt, war, vis, home):
        fb.op('Mov', dst=r, src=zi)
    fb.op('Mov', dst=sd, src=big)
    fb.op('Mov', dst=tc, src=zero)
    fb.op('JTrue', cond=b.field(g, 'removed'), offset='ab_gone')
    # members: alive / at war with us / visible / on their owner's own zone
    mem = b.field(g, 'entities')
    fb.op('JNull', reg=mem, offset='ab_gone')
    mn = b.field(mem, 'length')
    fb.op('Mov', dst=j, src=zi)
    b.loop_head('mem')
    fb.op('JSGte', a=j, b=mn, offset='mdone')
    e = b.cast(b.call('hl.types.ArrayObj.getDyn', mem, j), 'ent.Entity')
    fb.op('Incr', dst=j)
    fb.op('JNull', reg=e, offset='mem')
    fb.op('JTrue', cond=b.call('ent.Entity.isDead', e), offset='mem')
    eo = b.call('ent.Entity.get_owner', e)
    fb.op('JNull', reg=eo, offset='mem')
    fb.op('Add', dst=cnt, a=cnt, b=one)
    fb.op('Mov', dst=first, src=e)
    fb.op('Call2', dst=sdx, fun=land, arg0=fac, arg1=e)
    fb.op('JSGte', a=sdx, b=sd, offset='nomin')
    fb.op('Mov', dst=sd, src=sdx)
    fb.op('Mov', dst=core, src=e)
    fb.label('nomin')
    fb.op('JFalse', cond=b.call('logic.state.State.areAtWar', state, fac, eo), offset='nowar')
    fb.op('Add', dst=war, a=war, b=one)
    fb.label('nowar')
    fb.op('JFalse', cond=b.call('ent.Entity.isVisibleForFaction', e, fac), offset='novis')
    fb.op('Add', dst=vis, a=vis, b=one)
    fb.label('novis')
    z = b.call('ent.Entity.get_zone', e)
    fb.op('JNull', reg=z, offset='mem')
    fb.op('JNotEq', a=b.field(z, 'owner'), b=eo, offset='mem')
    fb.op('Add', dst=home, a=home, b=one)
    fb.op('JAlways', offset='mem')
    fb.label('mdone')
    # the group is judged at its core (the member nearest our land, sd), not at its centroid: a member walking home
    # dragged the centroid under its own base's guns and aborted a winning hunt as `weak`. Members more than LOCAL
    # from the core have split off: they leave the group, so the order's target (centroid) stays on the prey
    fb.op('Mov', dst=first, src=core)
    fb.op('Mov', dst=ent_r, src=core)
    fb.op('Mov', dst=j, src=mn)
    b.loop_head('prune')
    fb.op('JSLte', a=j, b=zi, offset='pdone')
    fb.op('Sub', dst=j, a=j, b=one)
    pe = b.cast(b.call('hl.types.ArrayObj.getDyn', mem, j), 'ent.Entity')
    fb.op('JNull', reg=pe, offset='prune')
    fb.op('JSLte', a=b.call('ent.Entity.getDistTo', pe, core), b=local, offset='prune')
    b.call('hl.types.ArrayObj.remove', mem, fb.dyn(pe))
    fb.op('JAlways', offset='prune')
    fb.label('pdone')
    # our side: power, nearest order army to the core, anyone short of supply for the way back
    units = b.field(o, 'units')
    fb.op('JNull', reg=units, offset='ab_gone')
    un = b.field(units, 'length')
    fb.op('Mov', dst=need, src=big)
    fb.op('Bool', dst=losing, value=False)
    u = _army_loop(fb, b, units, un, j, 'units', 'udone')
    fb.op('Call1', dst=p, fun=pw, arg0=u)
    fb.op('Add', dst=m, a=m, b=p)
    fb.op('Call2', dst=ok, fun=short, arg0=fac, arg1=u)
    fb.op('JFalse', cond=ok, offset='sup')  # hysteresis: the start needs SUP_ENTER x the budget
    fb.op('Bool', dst=losing, value=True)
    fb.label('sup')
    dd = b.call('ent.Entity.getDistTo', u, core)
    fb.op('JSGte', a=dd, b=need, offset='units')
    fb.op('Mov', dst=need, src=dd)
    fb.op('JAlways', offset='units')
    fb.label('udone')
    # triggers, in priority order (sd = the member nearest to our land, same measure as the start pass)
    fb.op('JSLte', a=cnt, b=zi, offset='ab_gone')
    fb.op('JSLte', a=war, b=zi, offset='ab_truce')
    fb.op('JSGt', a=sd, b=leash, offset='ab_leash')
    fb.op('JNotEq', a=home, b=cnt, offset='nothome')
    fb.op('JSGt', a=sd, b=home_exit, offset='ab_home')
    fb.label('nothome')
    fb.op('JTrue', cond=losing, offset='ab_supply')  # in contact too: turn back while the way home is affordable
    fb.op('JSLte', a=sd, b=drift_r, offset='nodrift')  # moving away from our land and we never caught up
    fb.op('JSGt', a=need, b=contact, offset='ab_drift')
    fb.label('nodrift')
    fb.op('JSGt', a=vis, b=zi, offset='seen')
    fb.op('JSGt', a=need, b=local, offset='ab_lost')
    fb.label('seen')
    fb.op('Call3', dst=h, fun=threat, arg0=fac, arg1=ent_r, arg2=local)
    # turret cover at the group: enemy turrets / main base guns add to the threat, ours to our power
    cover_at(tc, ent_r, no_ent, False)
    cover_at(tm, ent_r, no_ent, True)
    fb.op('Add', dst=h, a=h, b=tc)
    fb.op('Add', dst=m, a=m, b=tm)
    fb.op('Mul', dst=p, a=h, b=abort)
    fb.op('Call2', dst=tf, fun=terrain, arg0=fac, arg1=b.call('ent.Entity.get_zone', first))
    fb.op('SDiv', dst=p, a=p, b=tf)  # on their land we give up earlier, on ours later
    fb.op('JSLt', a=m, b=p, offset='ab_weak')
    # objective: a chase (no besieged village within LOCAL of its group) yields to a siege near our land that its
    # own armies could stop (same entry test as a contest start: free, within HUNT_R, supply budget, ENTER x
    # threat / terrain)
    fb.op('Null', dst=found)
    fb.op('Mov', dst=k, src=zi)
    b.loop_head('obj')
    fb.op('JSGte', a=k, b=vlen, offset='objdone')
    v = b.cast(b.call('hl.types.ArrayObj.getDyn', villages, k), 'ent.Structure')
    fb.op('Incr', dst=k)
    fb.op('JNull', reg=v, offset='obj')
    fb.op('Call2', dst=ok, fun=sieged, arg0=fac, arg1=v)
    fb.op('JFalse', cond=ok, offset='obj')
    fb.op('Mov', dst=ve, src=v)
    fb.op('JSLte', a=b.call('ent.Entity.getDistTo', g, ve), b=local, offset='ord')  # already contesting one
    fb.op('JNotNull', reg=found, offset='obj')
    fb.op('Call2', dst=sdx, fun=land, arg0=fac, arg1=ve)
    fb.op('JSGt', a=sdx, b=defend_r, offset='obj')
    mv = fb.reg(cx.t('f64'))
    fb.op('Mov', dst=mv, src=zero)
    uu = _army_loop(fb, b, units, un, j, 'ou', 'oudone')
    fb.op('JSGt', a=b.call('ent.Entity.getDistTo', uu, ve), b=hunt_r, offset='ou')
    fb.op('Call2', dst=ok, fun=free, arg0=uu, arg1=no_orders)
    fb.op('JFalse', cond=ok, offset='ou')
    fb.op('Call3', dst=ok, fun=supok, arg0=uu, arg1=sdx, arg2=sup_enter)
    fb.op('JFalse', cond=ok, offset='ou')
    fb.op('Call1', dst=p, fun=pw, arg0=uu)
    fb.op('Add', dst=mv, a=mv, b=p)
    fb.op('JAlways', offset='ou')
    fb.label('oudone')
    hv = fb.reg(cx.t('f64'))
    fb.op('Call3', dst=hv, fun=threat, arg0=fac, arg1=ve, arg2=local)
    cover_at(q, ve, ve, False)  # same measure as the contest start: + enemy cover, + our cover on our side
    fb.op('Add', dst=hv, a=hv, b=q)
    cover_at(q, ve, ve, True)
    fb.op('Add', dst=mv, a=mv, b=q)
    fb.op('Mul', dst=hv, a=hv, b=enter)
    fb.op('Call2', dst=tv, fun=terrain, arg0=fac, arg1=b.call('ent.Entity.get_zone', ve))
    fb.op('SDiv', dst=hv, a=hv, b=tv)
    fb.op('JSLt', a=mv, b=hv, offset='obj')
    fb.op('Mov', dst=found, src=ve)
    fb.op('JAlways', offset='obj')
    fb.label('objdone')
    fb.op('JNotNull', reg=found, offset='ab_objective')
    # defend: one of our structures is besieged -> a chase ends, unless the prey is in contact and we crush it
    # (h, tf: the group's threat and terrain from the `weak` test)
    fb.op('JNull', reg=dfs, offset='tur')
    fb.op('JSGt', a=need, b=contact, offset='ab_defend')
    fb.op('Mul', dst=q, a=h, b=kill)
    fb.op('SDiv', dst=q, a=q, b=tf)
    fb.op('JSLt', a=m, b=q, offset='ab_defend')
    # turret: a chase under enemy turret cover (a main base, a village's turrets) only while we are on the prey
    # and crush it (h includes the cover: we take a few shots and leave)
    fb.label('tur')
    fb.op('JSLte', a=tc, b=zero, offset='go')
    fb.op('JSGt', a=need, b=contact, offset='ab_turret')
    fb.op('Mul', dst=q, a=h, b=kill)
    fb.op('SDiv', dst=q, a=q, b=tf)
    fb.op('JSLt', a=m, b=q, offset='ab_turret')
    # go: vanilla Regroup waits until every army reached the regroup point, so the hunters next to the prey stood
    # still for the stragglers while single armies drifted into contact alone. Once the armies already within
    # LOCAL of the core (+ our cover) pass the entry test there (ENTER x threat / terrain), the order moves on to
    # Engage: everyone attacks now, the stragglers walk straight in (vanilla's own stall path does the same)
    fb.label('go')
    fb.op('JNotEq', a=b.field(o, 'phase'), b=b.const('i32', REGROUP), offset='ord')
    fb.op('Mov', dst=q, src=tm)
    ug = _army_loop(fb, b, units, un, j, 'gu', 'gudone')
    fb.op('JSGt', a=b.call('ent.Entity.getDistTo', ug, core), b=local, offset='gu')
    fb.op('Call1', dst=p, fun=pw, arg0=ug)
    fb.op('Add', dst=q, a=q, b=p)
    fb.op('JAlways', offset='gu')
    fb.label('gudone')
    fb.op('Mul', dst=tv, a=h, b=enter)
    fb.op('SDiv', dst=tv, a=tv, b=tf)
    fb.op('JSLt', a=q, b=tv, offset='ord')
    fb.op('Call1', dst=void, fun=helpers.get('nextPhase', cx.fn('logic.ai.AIOrder.nextPhase').findex.value), arg0=o)
    _log_hunt(fb, b, cx, helpers, fac, 'engage', None, first, h, q, {'sd': sd, 'dn': need, 'T': tc})
    fb.op('JAlways', offset='ord')
    fb.label('ab_nolog')
    b.call('logic.ai.AIOrder.stop', o, cancel)
    fb.op('JAlways', offset='ord')
    fb.label('ab_objective')
    b.call('logic.ai.AIOrder.stop', o, cancel)
    # start the contest at the next start pass: lift the start gap, and allow only contests for HUNT_GAP s
    # (no chase restart that this trigger would cancel again)
    tg = fb.reg(cx.t('f64'))
    fb.op('Sub', dst=tg, a=t, b=gap)
    b.call('haxe.ds.ObjectMap.set', lastmap, fb.dyn(fac), fb.dyn(tg))
    b.call('haxe.ds.ObjectMap.set', objmap, fb.dyn(fac), fb.dyn(t))
    _log_hunt(fb, b, cx, helpers, fac, 'abort', 'objective', first, h, m, {'sd': sd, 'dn': need, 'obj': found})
    fb.op('JAlways', offset='ord')
    fb.label('ab_defend')
    b.call('logic.ai.AIOrder.stop', o, cancel)
    fb.op('Mov', dst=ve, src=dfs)
    _log_hunt(fb, b, cx, helpers, fac, 'abort', 'defend', first, h, m, {'sd': sd, 'dn': need, 'obj': ve})
    fb.op('JAlways', offset='ord')
    for why in ('gone', 'truce', 'leash', 'home', 'supply', 'drift', 'lost', 'weak', 'turret'):
        fb.label(f'ab_{why}')
        b.call('logic.ai.AIOrder.stop', o, cancel)
        _log_hunt(fb, b, cx, helpers, fac, 'abort', why, first, h, m, {'sd': sd, 'dn': need, 'T': tc})
        fb.op('JAlways', offset='ord')

    # ---- 2. start pass: at most one new hunt
    fb.label('new')
    _tick(fb, b, cx, t, START, 'end')
    last = b.call('haxe.ds.ObjectMap.get', lastmap, fb.dyn(fac))
    lastf = fb.reg(cx.t('f64'))
    fb.op('JNull', reg=last, offset='gapok')
    fb.op('SafeCast', dst=lastf, src=last)
    fb.op('Sub', dst=lastf, a=t, b=lastf)
    fb.op('JSLt', a=lastf, b=gap, offset='end')
    fb.label('gapok')
    best_h, best_m, best_s = b.const('f64', 0), b.const('f64', 0), b.const('f64', 0)
    best_d, best_sd = b.const('f64', 0), b.const('f64', 0)
    best = fb.reg(cx.t('ent.Entity'))
    fb.op('Null', dst=best)
    anc, best_anc, prey = fb.reg(cx.t('ent.Entity')), fb.reg(cx.t('ent.Entity')), fb.reg(cx.t('ent.Entity'))
    fb.op('Null', dst=best_anc)
    dmin, w, sc = fb.reg(cx.t('f64')), fb.reg(cx.t('f64')), fb.reg(cx.t('f64'))
    one_f, contest_w, dist0 = b.const('f64', 1), b.const('f64', CONTEST_W), b.const('f64', DIST0)
    mode = fb.reg(cx.t('i32'))
    fb.op('Mov', dst=mode, src=zi)
    rr, best_rr = fb.reg(cx.t('f64')), fb.reg(cx.t('f64'))  # join radius of the candidate / of the best
    fb.op('Mov', dst=best_rr, src=hunt_r)
    best_t = b.const('f64', 0)  # enemy turret cover at the chosen anchor (logged as T)
    fb.op('Call1', dst=dfs, fun=defend, arg0=fac)
    # right after an `objective` abort only contests may start
    lo = b.call('haxe.ds.ObjectMap.get', objmap, fb.dyn(fac))
    fb.op('JNull', reg=lo, offset='chase')
    fb.op('SafeCast', dst=lastf, src=lo)
    fb.op('Sub', dst=lastf, a=t, b=lastf)
    fb.op('JSLt', a=lastf, b=gap, offset='cdone')
    fb.label('chase')
    # (a) chase candidates: visible at-war armies near our land
    e = _army_loop(fb, b, armies, alen, i, 'cand', 'cdone')
    eo = b.call('ent.Entity.get_owner', e)
    fb.op('JNull', reg=eo, offset='cand')
    fb.op('JEq', a=eo, b=fac, offset='cand')
    fb.op('JFalse', cond=b.call('logic.state.State.areAtWar', state, fac, eo), offset='cand')
    fb.op('JFalse', cond=b.call('ent.Entity.isVisibleForFaction', e, fac), offset='cand')
    fb.op('Mov', dst=ent_r, src=e)
    fb.op('Call2', dst=sd, fun=land, arg0=fac, arg1=ent_r)
    fb.op('JSGt', a=sd, b=defend_r, offset='cand')  # only intruders near our land (defensive posture)
    z = b.call('ent.Entity.get_zone', e)
    fb.op('JNull', reg=z, offset='away')
    fb.op('JNotEq', a=b.field(z, 'owner'), b=eo, offset='away')
    fb.op('JSGt', a=sd, b=home_r, offset='cand')  # on its own land: only right next to us
    fb.label('away')
    fb.op('Mov', dst=anc, src=e)
    fb.op('Mov', dst=prey, src=e)
    fb.op('Mov', dst=w, src=one_f)
    fb.op('Mov', dst=rr, src=hunt_r)
    fb.op('JAlways', offset='eval')
    # (b) contest candidates: villages near our land besieged by an at-war faction (objective: weight CONTEST_W,
    # the group is anchored on the village)
    fb.label('cdone')
    fb.op('Mov', dst=mode, src=one)
    fb.op('Mov', dst=i, src=zi)
    b.loop_head('vcand')
    fb.op('JSGte', a=i, b=vlen, offset='vdone')
    v = b.cast(b.call('hl.types.ArrayObj.getDyn', villages, i), 'ent.Structure')
    fb.op('Incr', dst=i)
    fb.op('JNull', reg=v, offset='vcand')
    fb.op('Call2', dst=ok, fun=sieged, arg0=fac, arg1=v)
    fb.op('JFalse', cond=ok, offset='vcand')
    fb.op('Mov', dst=ent_r, src=v)
    fb.op('Call2', dst=sd, fun=land, arg0=fac, arg1=ent_r)
    fb.op('JSGt', a=sd, b=defend_r, offset='vcand')
    fb.op('Mov', dst=rr, src=hunt_r)
    fb.op('JNotEq', a=b.call('ent.Entity.get_owner', ent_r), b=fac, offset='notown')
    fb.op('Mov', dst=rr, src=gather_r)  # our own village: everyone free comes (vanilla Regroup gathers them)
    fb.op('JAlways', offset='vown')
    fb.label('notown')
    fb.op('JNotNull', reg=dfs, offset='vcand')  # defending: our own villages first
    fb.label('vown')
    fb.op('Mov', dst=anc, src=ent_r)
    fb.op('Mov', dst=prey, src=ent_r)
    fb.op('Mov', dst=w, src=contest_w)
    # shared evaluation (anc, prey, w, sd = anc's distance to our land)
    fb.label('eval')
    fb.op('Call3', dst=h, fun=threat, arg0=fac, arg1=anc, arg2=local)
    fb.op('Call3', dst=p, fun=threat, arg0=fac, arg1=prey, arg2=local)  # the abort pass looks at the group
    fb.op('JSGte', a=h, b=p, offset='hmax')
    fb.op('Mov', dst=h, src=p)
    fb.label('hmax')
    # turret cover at the anchor (not the anchor's own turrets: a besieged village's turrets are silent)
    cover_at(tc, anc, anc, False)
    fb.op('Add', dst=h, a=h, b=tc)
    cover_at(tm, anc, anc, True)
    fb.op('Mov', dst=m, src=tm)  # our turrets there fight with us
    fb.op('Mov', dst=dmin, src=big)
    y = _army_loop(fb, b, my_armies, mlen, j, 'mloop', 'mdone2')
    dy = b.call('ent.Entity.getDistTo', y, anc)
    fb.op('JSGt', a=dy, b=rr, offset='mloop')
    fb.op('Call2', dst=ok, fun=free, arg0=y, arg1=orders)
    fb.op('JFalse', cond=ok, offset='mloop')
    fb.op('Call3', dst=ok, fun=supok, arg0=y, arg1=sd, arg2=sup_enter)  # supply for the way back from there
    fb.op('JFalse', cond=ok, offset='mloop')
    fb.op('Call1', dst=p, fun=pw, arg0=y)
    fb.op('Add', dst=m, a=m, b=p)
    fb.op('JSGte', a=dy, b=dmin, offset='mloop')
    fb.op('Mov', dst=dmin, src=dy)
    fb.op('JAlways', offset='mloop')
    fb.label('mdone2')
    fb.op('JSGte', a=dmin, b=big, offset='next')  # no free army in reach (our turrets alone don't hunt)
    fb.op('Mul', dst=need, a=h, b=enter)
    fb.op('Call2', dst=tf, fun=terrain, arg0=fac, arg1=b.call('ent.Entity.get_zone', anc))
    fb.op('SDiv', dst=need, a=need, b=tf)  # their land: 1.5 / 0.8 = 1.9x needed; ours: 1.15x
    fb.op('JSLt', a=m, b=need, offset='next')
    # a chase while we defend, or under enemy turret cover: only when the prey is in contact and we have KILL x
    # (its threat + cover)
    fb.op('JEq', a=mode, b=one, offset='score')
    fb.op('JNotNull', reg=dfs, offset='restrict')
    fb.op('JSLte', a=tc, b=zero, offset='score')
    fb.label('restrict')
    fb.op('JSGt', a=dmin, b=contact, offset='next')
    fb.op('Mul', dst=q, a=need, b=kill_x)
    fb.op('JSLt', a=m, b=q, offset='next')
    fb.label('score')
    # score = weight * threat / (distance of our nearest free army + DIST0): near and objective-bound first
    fb.op('Add', dst=sc, a=dmin, b=dist0)
    fb.op('Mul', dst=p, a=w, b=h)
    fb.op('SDiv', dst=sc, a=p, b=sc)
    fb.op('JSLte', a=sc, b=best_s, offset='next')
    fb.op('Mov', dst=best_s, src=sc)
    fb.op('Mov', dst=best_d, src=dmin)
    fb.op('Mov', dst=best_h, src=h)
    fb.op('Mov', dst=best_m, src=m)
    fb.op('Mov', dst=best_sd, src=sd)
    fb.op('Mov', dst=best_rr, src=rr)
    fb.op('Mov', dst=best_t, src=tc)
    fb.op('Mov', dst=best, src=prey)
    fb.op('Mov', dst=best_anc, src=anc)
    fb.label('next')
    fb.op('JEq', a=mode, b=one, offset='vcand')
    fb.op('JAlways', offset='cand')
    fb.label('vdone')
    fb.op('JNull', reg=best, offset='end')
    fb.op('Mov', dst=sd, src=best_sd)  # logged sd = the chosen anchor's

    # our free armies in reach (same tests as the evaluation)
    arr = _new_array(fb, b, cx)
    y = _army_loop(fb, b, my_armies, mlen, j, 'gloop', 'gdone')
    fb.op('JSGt', a=b.call('ent.Entity.getDistTo', y, best_anc), b=best_rr, offset='gloop')
    fb.op('Call2', dst=ok, fun=free, arg0=y, arg1=orders)
    fb.op('JFalse', cond=ok, offset='gloop')
    fb.op('Call3', dst=ok, fun=supok, arg0=y, arg1=sd, arg2=sup_enter)
    fb.op('JFalse', cond=ok, offset='gloop')
    b.call('hl.types.ArrayObj.push', arr, fb.dyn(y))
    fb.op('JAlways', offset='gloop')
    fb.label('gdone')
    # target = group of every at-war army around the anchor (the besieged village for a contest, else the prey;
    # vanilla checkStructures pattern; the group drops dead members and removes itself when empty;
    # checkEngageOrder requires a Group target for ArmyFight)
    garr = _new_array(fb, b, cx)
    x = _army_loop(fb, b, armies, alen, j, 'grp', 'grpdone')
    xo = b.call('ent.Entity.get_owner', x)
    fb.op('JNull', reg=xo, offset='grp')
    fb.op('JEq', a=xo, b=fac, offset='grp')
    fb.op('JSGt', a=b.call('ent.Entity.getDistTo', x, best_anc), b=local, offset='grp')
    fb.op('JFalse', cond=b.call('logic.state.State.areAtWar', state, fac, xo), offset='grp')
    b.call('hl.types.ArrayObj.push', garr, fb.dyn(x))
    fb.op('JAlways', offset='grp')
    fb.label('grpdone')
    fb.op('JSLte', a=b.field(garr, 'length'), b=zi, offset='end')  # siege state but no besieger in reach
    create = cx.fn('logic.ai.$AIEntityGroup.create')
    nul = fb.reg(cx.code.types[create.type.value].definition.args[1].value)
    fb.op('Null', dst=nul)
    grp = fb.reg(cx.t('logic.ai.AIEntityGroup'))
    fb.op('Call2', dst=grp, fun=create.findex.value, arg0=garr, arg1=nul)

    add = cx.fn('logic.ai.AIOrders.addOrder')
    at = [a.value for a in cx.code.types[add.type.value].definition.args]
    kind = fb.reg(cx.t('logic.ai.AIOrderType'))
    fb.op('MakeEnum', dst=kind, construct=MILITARY, args=[])
    fb.op('Mov', dst=ent_r, src=grp)
    nulls = []
    for n in (6, 7, 8, 9, 10):  # sa, mm, om, data, onComplete
        r = fb.reg(at[n])
        fb.op('Null', dst=r)
        nulls.append(r)
    res = fb.reg(cx.t('logic.ai.AIOrder'))
    fb.op('CallN', dst=res, fun=helpers.get('addOrder', add.findex.value),
          args=[orders_obj, kind, b.const('i32', 5), arr, ent_r, fb.string('ArmyFight')] + nulls)
    fb.op('Bool', dst=ok, value=False)
    fb.op('JNull', reg=res, offset='fail')
    fb.op('Bool', dst=ok, value=True)
    b.call('haxe.ds.ObjectMap.set', lastmap, fb.dyn(fac), fb.dyn(t))
    fb.label('fail')
    _log_hunt(fb, b, cx, helpers, fac, 'start', None, best, best_h, best_m,
              {'n': b.field(arr, 'length'), 'ng': b.field(garr, 'length'), 'ok': ok, 'sd': sd, 'dm': best_d,
               'anc': best_anc, 'T': best_t})
    fb.label('end')
    fb.end_try(guard)
    fb.op('Ret', ret=void)
    return fb.build()
