"""Siege force: `siege-join` (vanilla pickUnits sizing: nearest idle armies join until JOIN_TO x the defense,
sietch / renegade floors, ground pick) and `siege-engage` (our siege orders leave Regroup once the armies near the
target pass enter)."""
from rules.common import *  # noqa: F401,F403  thresholds (AI-POLICY §4) and bytecode helpers


def build_join(cx, helpers, supok, land, pw, threat, cover, militia, terrain, new_ids, neutral, sqr):
    """Siege launch sizing: the pickUnits call(s) in tryArmyAction (every vanilla siege launch after the gate).
    Vanilla requires balance 1.0 flat for a neutral target and adds idle armies closest-first only until it is
    reached, so a village gets 2 armies while more sit idle next to it: the militia fight drags on (~50 s), drains
    supply the whole time and can kill one of the two (Fremen on Ashdak, 3 attempts, 18 bunker redirects, none taken).
    0. vanilla's candidates (consideredUnits) lose armies on a Discovery trip farther than JOIN_R from the target and,
       unless a free Supply Drop is held, armies whose walk there fails vanilla's siege supply check (SUP_U x distance
       > SD_VAN_K x supply: one such army cancels the whole order with InsufficientSupply; log `trippick`);
    1. owned target (targetFaction set): requiredPowerBalance raised to OWNED_REQ; neutral target (targetFaction null): raised to NEUTRAL_REQ, except in the opening (we own
       fewer than EARLY_VILLAGES villages: vanilla's EARLY_REQ, so the starting armies take the first villages); a
       sietch or a renegade base: ENTER;
    3. a sietch / renegade base: fewer than SIETCH_ARMIES / RENEGADE_ARMIES armies (its garrison) -> empty pick,
       logs `sfloor`; a simulated pick only when we own fewer armies than that (vanilla then recruits instead of
       waiting);
    2. after the pick (and until aimod_sqr vs its militia reaches SQ_MIN), the nearest other considered armies (vanilla getUnits idle list: life/supply >= 90%, not in
       an order of the action's priority or higher, so Discovery/Patrol armies are taken as vanilla does) within
       JOIN_R of the target with supok(a, land(target), SUP_ENTER) and a walk there within vanilla's siege supply check
       (SUP_U x distance <= SD_VAN_K x supply) are appended one by one until our power there
       (+ our turret cover x OWN_COVER_ATK; a sietch / renegade base: armies only, terrain 1) reaches JOIN_TO x (at-war threat within LOCAL + enemy turret cover + militia) / terrain
       (a sietch / renegade base: and the army floor of 3.):
       a short militia fight, while the rest stays free for parallel captures (joining everyone sent 8 armies to a
       33k militia at match start and made captures sequential).
    4. a sietch / renegade base still below ENTER x that side / terrain after joining (our measure; vanilla's own
       estimate passes picks ours puts at 1.4) -> empty pick, logs `sweak` (vanilla: NotEnoughArmies / recruits).
    Simulated picks (simulatePendingArmies: counts armies in recruitment) pass through unchanged. Logs `join` when
    armies were added (H, M = the power after joining). Original result on any error."""
    pick = cx.fn('logic.ai.AIUnits.pickUnits')
    taa = cx.fn('logic.ai.AIMilitary.tryArmyAction')
    ftypes = {f.findex.value: f.type.value for f in cx.code.functions}
    sites = [op for op in taa.ops if op.op == 'Call2' and ftypes.get(op.df['fun'].value) == pick.type.value]
    if len(sites) != 3:
        raise ValueError(f'siege-join: expected 3 pickUnits calls in tryArmyAction, found {len(sites)}')
    inner = {op.df['fun'].value for op in sites}
    if len(inner) != 1:
        raise ValueError(f'siege-join: pickUnits call sites differ ({inner})')
    inner = inner.pop()  # the logging wrapper when installed (same signature)
    ft = cx.code.types[pick.type.value].definition
    args = [a.value for a in ft.args]
    fb = FB(cx, args, ft.ret.value, fun_type=pick.type.value)
    b = B(fb)
    res = fb.reg(ft.ret.value)
    req = fb.reg(cx.t('f64'))
    fb.op('Mov', dst=req, src=b.const('f64', 0))
    sim = fb.reg(cx.t('bool'))
    fb.op('Bool', dst=sim, value=False)
    # 1. required ratio for neutral targets
    guard = fb.try_()
    sp, _ = _vfield(fb, b, 1, 'simulatePendingArmies')
    fb.op('JNull', reg=sp, offset='nosim')
    fb.op('SafeCast', dst=sim, src=sp)
    fb.label('nosim')
    fb.op('JTrue', cond=sim, offset='req_done')
    enter = _ratio(fb, b, NEUTRAL_REQ)
    # opening: fewer than EARLY_VILLAGES villages -> vanilla's EARLY_REQ (the first captures with the starting armies)
    owner = b.call('logic.ai.AIModule.get_aiOwner', 0)
    fb.op('JNull', reg=owner, offset='req_early')
    fb.op('JSGte', a=b.field(b.call('ent.Faction.getVillages', owner), 'length'), b=b.const('i32', EARLY_VILLAGES),
          offset='req_early')
    fb.op('Mov', dst=enter, src=_ratio(fb, b, EARLY_REQ))
    fb.label('req_early')
    # a renegade base (Dismantle) or a sietch (PillageSietch): its garrison and spawns make a fight at NEUTRAL_REQ a
    # coin toss (Atreides lost Dismantles at est 1.26 / 1.33, won at 1.64; Smugglers' whole army, 8 armies at est
    # 1.32, lost Bur-Al'ur's sietch); ENTER lost too (the sietch adds its 3 harass units mid-strike): SITE_REQ, as at the target
    rb0, _ = _vfield(fb, b, 1, 'enemyStructure')
    fb.op('JNull', reg=rb0, offset='req_rb')
    rbs = b.cast(fb.dyn(rb0), 'ent.Structure')
    fb.op('JNull', reg=rbs, offset='req_rb')
    fb.op('JTrue', cond=b.call('ent.Structure.isSietch', rbs), offset='req_strong')
    fb.op('JFalse', cond=b.call('ent.Structure.isRenegadeBase', rbs), offset='req_rb')
    fb.label('req_strong')
    fb.op('Mov', dst=enter, src=_ratio(fb, b, SITE_REQ))
    fb.label('req_rb')
    rq, ri = _vfield(fb, b, 1, 'requiredPowerBalance')
    fb.op('JNull', reg=rq, offset='req_tf')
    fb.op('SafeCast', dst=req, src=rq)
    fb.label('req_tf')
    tfac, _ = _vfield(fb, b, 1, 'targetFaction')
    # an owned target (at-war village): at least OWNED_REQ (35 such attacks reaching the fight, matches 2026-10-04:
    # req < 1.25 won 0 of 7 and lost 18 armies, est < 1.3 0 of 5 with 15 dead)
    fb.op('JNull', reg=tfac, offset='req_neu')
    fb.op('Mov', dst=enter, src=_ratio(fb, b, OWNED_REQ))
    # ... x (1 + (its distance from our land - OWNED_D0) / OWNED_DK): a deep attack can't retreat (Harkonnen's Zanit
    # 415 away lost 7 of 12 walking home from Smugglers' relief, Smugglers' Sinwaz 877 away 4 of 8)
    fb.op('JNull', reg=owner, offset='req_neu')
    oes, _ = _vfield(fb, b, 1, 'enemyStructure')
    fb.op('JNull', reg=oes, offset='req_neu')
    oe = fb.reg(cx.t('ent.Entity'))
    fb.op('Mov', dst=oe, src=b.cast(fb.dyn(oes), 'ent.Entity'))
    fb.op('JNull', reg=oe, offset='req_neu')
    odl = fb.reg(cx.t('f64'))
    fb.op('Call2', dst=odl, fun=land, arg0=owner, arg1=oe)
    fb.op('Sub', dst=odl, a=odl, b=b.const('f64', OWNED_D0))
    fb.op('JSLte', a=odl, b=b.const('f64', 0), offset='req_neu')
    fb.op('SDiv', dst=odl, a=odl, b=b.const('f64', OWNED_DK))
    fb.op('Add', dst=odl, a=odl, b=b.const('f64', 1))
    fb.op('Mul', dst=enter, a=enter, b=odl)
    # capped at OWNED_REQ_MAX: a clearly stronger force still goes, however far (user: never skip a distant enemy
    # village while holding double its side)
    fb.op('JSLte', a=enter, b=_ratio(fb, b, OWNED_REQ_MAX), offset='req_neu')
    fb.op('Mov', dst=enter, src=_ratio(fb, b, OWNED_REQ_MAX))
    fb.label('req_neu')
    # a neutral village whose militia beat us lately: NBUMP_K more (common._nbump; no lost-siege block)
    fb.op('JNull', reg=rb0, offset='req_nbd')
    nbe = fb.reg(cx.t('ent.Entity'))
    fb.op('Mov', dst=nbe, src=b.cast(fb.dyn(rb0), 'ent.Entity'))
    _nbump(fb, b, cx, owner, nbe, enter)
    fb.label('req_nbd')
    fb.op('JNull', reg=rq, offset='req_set')
    fb.op('JSGte', a=req, b=enter, offset='req_hi')
    fb.label('req_set')
    fb.op('Mov', dst=req, src=enter)
    # owned target: never above OWNED_REQ_TOP. Vanilla draws its own uniformly in AI_PowerBalance_Attack_Min..Max
    # (Insane 1.0..3.5, getAttackRandomPowerBalance): Smugglers' picks on Atreides / Harkonnen villages asked
    # 2.5-3.4 (match 08:11; user: double their army must attack)
    fb.label('req_hi')
    fb.op('JNull', reg=tfac, offset='req_w')
    fb.op('JSLte', a=req, b=_ratio(fb, b, OWNED_REQ_TOP), offset='req_w')
    fb.op('Mov', dst=req, src=_ratio(fb, b, OWNED_REQ_TOP))
    fb.label('req_w')
    nr = fb.reg(fb.regs[rq])
    fb.op('ToDyn', dst=nr, src=req)  # Null<Float>, the way the compiler boxes it
    fb.op('SetField', obj=1, field=ri, src=nr)
    fb.label('req_done')
    fb.end_try(guard)
    # 0. armies on a Discovery trip farther than JOIN_R from the target leave the candidates (vanilla pulled one ~370
    # away into Fremen's Annex of Haykus: the stack arrived strung out)
    guard0 = fb.try_()
    fb.op('JTrue', cond=sim, offset='fd_done')
    es0, _ = _vfield(fb, b, 1, 'enemyStructure')
    fb.op('JNull', reg=es0, offset='fd_done')
    s0 = fb.reg(cx.t('ent.Entity'))
    fb.op('SafeCast', dst=s0, src=fb.dyn(es0))
    cu0, _ = _vfield(fb, b, 1, 'consideredUnits')
    fb.op('JNull', reg=cu0, offset='fd_done')
    cand0 = fb.reg(cx.t('hl.types.ArrayObj'))
    fb.op('SafeCast', dst=cand0, src=fb.dyn(cu0))
    ords0 = b.field(b.field(b.field(0, 'controller'), 'aiOrders'), 'orders')
    fb.op('JNull', reg=ords0, offset='fd_done')
    fi0, fk0, fx0 = (fb.reg(cx.t('i32')) for _ in range(3))
    fd0 = fb.reg(cx.t('f64'))
    fe0 = fb.reg(cx.t('ent.Entity'))
    # a free Supply Drop (map `sdfree` within SD_FRESH): sdrop-trip lifts vanilla's supply check, no trip filter
    trip0 = fb.reg(cx.t('bool'))
    fb.op('Bool', dst=trip0, value=True)
    sdf0 = b.call('haxe.ds.ObjectMap.get', _global_map(fb, b, cx, 'sdfree'), fb.dyn(b.field(b.field(0, 'controller'), 'owner')))
    fb.op('JNull', reg=sdf0, offset='trip0')
    sdq0 = fb.reg(cx.t('f64'))
    fb.op('SafeCast', dst=sdq0, src=sdf0)
    fb.op('Sub', dst=sdq0, a=b.field(_state(fb, b, cx), 'time'), b=sdq0)
    fb.op('JSGt', a=sdq0, b=b.const('f64', SD_FRESH), offset='trip0')
    fb.op('Bool', dst=trip0, value=False)
    fb.label('trip0')
    fb.op('Mov', dst=fi0, src=b.field(cand0, 'length'))
    b.loop_head('fdl')  # backwards: removal shifts the tail
    fb.op('JSLte', a=fi0, b=b.const('i32', 0), offset='fd_done')
    fb.op('Sub', dst=fi0, a=fi0, b=b.const('i32', 1))
    fa0 = b.cast(b.call('hl.types.ArrayObj.getDyn', cand0, fi0), 'ent.Army')
    fb.op('JNull', reg=fa0, offset='fdl')
    fb.op('Mov', dst=fe0, src=fa0)
    fb.op('Mov', dst=fd0, src=b.call('ent.Entity.getDistTo', fe0, s0))
    # an army whose walk there fails vanilla's siege supply check (path cost > SD_VAN_K x supply; path ~ SUP_U x
    # distance) leaves the candidates: picked, it cancels the whole order at once with InsufficientSupply (Fremen's
    # Annex of Rabnih 06:10 / 25:15 / 26:32, Cancel +1 s each); with nobody in reach vanilla gets NotEnoughArmies
    fb.op('JFalse', cond=trip0, offset='fdtrip')
    fms0 = b.call('ent.Army.get_maxSupply', fa0)
    fb.op('JSLte', a=fms0, b=b.const('f64', 0), offset='fdtrip')
    ftc0, fts0 = fb.reg(cx.t('f64')), fb.reg(cx.t('f64'))
    # a worm ride available (rules/ride.py): the ride plan's walking legs only (vanilla's worm plan has no supply
    # check; the ride itself costs no supply)
    fb.op('Mov', dst=ftc0, src=fd0)
    _ride_leg(fb, b, cx, b.field(b.field(0, 'controller'), 'owner'), b.field(_state(fb, b, cx), 'time'), ftc0)
    fb.op('Mul', dst=ftc0, a=ftc0, b=_ratio(fb, b, SUP_U))
    fb.op('Mul', dst=fts0, a=b.call('ent.Army.get_supply', fa0), b=_ratio(fb, b, SD_VAN_K))
    fb.op('JSLte', a=ftc0, b=fts0, offset='fdtrip')
    b.call('hl.types.ArrayObj.remove', cand0, fb.dyn(fa0))
    _throttle(fb, b, cx, 'trippick', fa0, PICK_LOG_T, 'fdl')
    _log_ev(fb, b, cx, helpers, 'trippick', [('f', fb.get(b.call('ent.Entity.get_owner', fe0), 'kind')), ('a', fa0),
                                             ('tgt', s0), ('d', fd0), ('sup', b.call('ent.Army.get_supply', fa0))])
    fb.op('JAlways', offset='fdl')
    fb.label('fdtrip')
    fb.op('JSLte', a=fd0, b=b.const('f64', JOIN_R), offset='fdl')
    fb.op('Mov', dst=fk0, src=b.field(ords0, 'length'))
    b.loop_head('fdo')
    fb.op('JSLte', a=fk0, b=b.const('i32', 0), offset='fdl')
    fb.op('Sub', dst=fk0, a=fk0, b=b.const('i32', 1))
    fo0 = b.cast(b.call('hl.types.ArrayObj.getDyn', ords0, fk0), 'logic.ai.AIOrder')
    fb.op('JNull', reg=fo0, offset='fdo')
    fu0 = b.field(fo0, 'units')
    fb.op('JNull', reg=fu0, offset='fdo')
    fb.op('JFalse', cond=b.call('hl.types.ArrayObj.contains', fu0, fb.dyn(fa0)), offset='fdo')
    fb.op('EnumIndex', dst=fx0, value=b.field(fo0, 'type'))
    fb.op('JNotEq', a=fx0, b=b.const('i32', DISCOVERY), offset='fdl')
    b.call('hl.types.ArrayObj.remove', cand0, fb.dyn(fa0))
    _throttle(fb, b, cx, 'farpick', fa0, PICK_LOG_T, 'fdl')
    _log_ev(fb, b, cx, helpers, 'farpick', [('f', fb.get(b.call('ent.Entity.get_owner', fe0), 'kind')), ('a', fa0),
                                            ('tgt', s0), ('d', fd0)])
    fb.op('JAlways', offset='fdl')
    fb.label('fd_done')
    fb.end_try(guard0)
    fb.op('Call2', dst=res, fun=inner, arg0=0, arg1=1)
    # 2. idle armies near the target join
    guard2 = fb.try_()
    fb.op('JTrue', cond=sim, offset='done')
    fb.op('JNull', reg=res, offset='done')
    n0 = b.field(res, 'length')
    fb.op('JSLte', a=n0, b=b.const('i32', 0), offset='done')
    fac = b.field(b.field(0, 'controller'), 'owner')
    fb.op('JNull', reg=fac, offset='done')
    es, _ = _vfield(fb, b, 1, 'enemyStructure')
    fb.op('JNull', reg=es, offset='done')
    s = fb.reg(cx.t('ent.Entity'))
    fb.op('SafeCast', dst=s, src=fb.dyn(es))
    cu, _ = _vfield(fb, b, 1, 'consideredUnits')
    fb.op('JNull', reg=cu, offset='done')
    cand = fb.reg(cx.t('hl.types.ArrayObj'))
    fb.op('SafeCast', dst=cand, src=fb.dyn(cu))
    cn = b.field(cand, 'length')
    d_home = fb.reg(cx.t('f64'))
    fb.op('Call2', dst=d_home, fun=land, arg0=fac, arg1=s)
    k = _ratio(fb, b, SUP_ENTER)
    r = b.const('f64', JOIN_R)
    added = fb.reg(cx.t('i32'))
    fb.op('Mov', dst=added, src=b.const('i32', 0))
    ok = fb.reg(cx.t('bool'))
    ae = fb.reg(cx.t('ent.Entity'))
    i = fb.reg(cx.t('i32'))
    h, m, p, q, tf, dd, bd = (fb.reg(cx.t('f64')) for _ in range(7))
    t_false, t_true = fb.reg(cx.t('bool')), fb.reg(cx.t('bool'))
    fb.op('Bool', dst=t_false, value=False)
    fb.op('Bool', dst=t_true, value=True)
    no_arr = fb.reg(cx.t('hl.types.ArrayObj'))
    fb.op('Null', dst=no_arr)
    st = b.cast(fb.dyn(s), 'ent.Structure')
    # their side (same measure as siege-engage) and the power we want there: JOIN_TO x that / terrain
    fb.op('Call3', dst=h, fun=threat, arg0=fac, arg1=s, arg2=b.const('f64', LOCAL))
    fb.op('CallN', dst=q, fun=cover, args=[fac, s, s, t_false, no_arr])
    fb.op('Add', dst=h, a=h, b=q)
    fb.op('Call1', dst=q, fun=militia, arg0=st)
    fb.op('Add', dst=h, a=h, b=q)
    # neutral raiders at it working for themselves (renegades taking it over, another faction's raiders): they
    # fight whoever contests the village (threat counts only raiders aimed at us)
    fb.op('Call3', dst=q, fun=neutral, arg0=fac, arg1=s, arg2=b.const('f64', LOCAL))
    fb.op('Add', dst=h, a=h, b=q)
    fb.op('Call2', dst=tf, fun=terrain, arg0=fac, arg1=b.call('ent.Entity.get_zone', s))
    _strong_tf(fb, b, tf, st)
    fb.op('Mul', dst=q, a=h, b=_ratio(fb, b, JOIN_TO))
    fb.op('SDiv', dst=q, a=q, b=tf)
    # ours: vanilla's pick (+ our turret cover there, x OWN_COVER_ATK; none at a sietch / renegade base)
    fb.op('CallN', dst=m, fun=cover, args=[fac, s, s, t_true, no_arr])
    _atk_cover(fb, b, m, st)
    sa = _army_loop(fb, b, res, n0, i, 'sl', 'sdone')
    fb.op('Call1', dst=p, fun=pw, arg0=sa)
    fb.op('Add', dst=m, a=m, b=p)
    fb.op('JAlways', offset='sl')
    fb.label('sdone')
    # a sietch / renegade base: also until the army floor (3.)
    jmin = fb.reg(cx.t('i32'))
    fb.op('Mov', dst=jmin, src=b.const('i32', 0))
    fb.op('JNull', reg=st, offset='jmin_done')
    fb.op('Mov', dst=jmin, src=b.const('i32', SIETCH_ARMIES))
    fb.op('JTrue', cond=b.call('ent.Structure.isSietch', st), offset='jmin_done')
    fb.op('Mov', dst=jmin, src=b.const('i32', RENEGADE_ARMIES))
    fb.op('JTrue', cond=b.call('ent.Structure.isRenegadeBase', st), offset='jmin_done')
    fb.op('Mov', dst=jmin, src=b.const('i32', 0))
    fb.label('jmin_done')
    # add the nearest eligible idle army until we have q
    best = fb.reg(cx.t('ent.Army'))
    big = b.const('f64', 1 << 30)
    sqv = fb.reg(cx.t('f64'))
    sqm = fb.reg(cx.t('f64'))
    fb.op('Mov', dst=sqm, src=_ratio(fb, b, SQ_MIN))
    _nbump(fb, b, cx, fac, s, sqm)  # a neutral village whose militia beat us lately: a little more
    b.loop_head('jo')
    fb.op('JSLt', a=m, b=q, offset='jgo')
    fb.op('JSLt', a=b.field(res, 'length'), b=jmin, offset='jgo')
    # and until the square law vs its militia holds (rules/sqlaw.py: 2 armies at 1.75x summed power vs 3-6 squads
    # won 55-59%; at SQ_MIN 97%)
    fb.op('JNull', reg=st, offset='jdone')
    fb.op('Call2', dst=sqv, fun=sqr, arg0=res, arg1=st)
    fb.op('JSGte', a=sqv, b=sqm, offset='jdone')
    fb.label('jgo')
    fb.op('Null', dst=best)
    fb.op('Mov', dst=bd, src=big)
    a = _army_loop(fb, b, cand, cn, i, 'jl', 'jpick')
    fb.op('JFalse', cond=b.call('hl.types.ArrayObj.contains', res, fb.dyn(a)), offset='jnew')
    fb.op('JAlways', offset='jl')
    fb.label('jnew')
    fb.op('Mov', dst=ae, src=a)
    fb.op('Mov', dst=dd, src=b.call('ent.Entity.getDistTo', ae, s))
    fb.op('JSGt', a=dd, b=r, offset='jl')
    fb.op('JSGte', a=dd, b=bd, offset='jl')
    fb.op('Call3', dst=ok, fun=supok, arg0=a, arg1=d_home, arg2=k)
    fb.op('JFalse', cond=ok, offset='jl')
    # ... and its walk to the target passes vanilla's siege supply check (InsufficientSupply when the path cost >
    # SD_VAN_K x the lowest order army's supply: one joined army cancels the whole order at once; Fremen's Annex of
    # Rabnih 06:10 / 26:32, add=1, Cancel +1 s InsufficientSupply). Path ~ SUP_U x straight distance (margin incl.)
    jms = b.call('ent.Army.get_maxSupply', a)
    fb.op('JSLte', a=jms, b=b.const('f64', 0), offset='jtrip')
    jtc, jts = fb.reg(cx.t('f64')), fb.reg(cx.t('f64'))
    fb.op('Mul', dst=jtc, a=dd, b=_ratio(fb, b, SUP_U))
    fb.op('Mul', dst=jts, a=b.call('ent.Army.get_supply', a), b=_ratio(fb, b, SD_VAN_K))
    fb.op('JSGt', a=jtc, b=jts, offset='jl')
    fb.label('jtrip')
    fb.op('Mov', dst=best, src=a)
    fb.op('Mov', dst=bd, src=dd)
    fb.op('JAlways', offset='jl')
    fb.label('jpick')
    fb.op('JNull', reg=best, offset='jdone')
    b.call('hl.types.ArrayObj.push', res, fb.dyn(best))
    fb.op('Incr', dst=added)
    fb.op('Call1', dst=p, fun=pw, arg0=best)
    fb.op('Add', dst=m, a=m, b=p)
    fb.op('JAlways', offset='jo')
    fb.label('jdone')
    # 4. a sietch / renegade base the joined force can't take at SITE_REQ by our measure (the one siege-engage judges):
    # empty pick (vanilla's own estimate passed Smugglers' whole army, 10 armies, 6 of them Sneaks / Demos / a
    # Drone, at 1.42 on Qaf-tah's 289k militia: -80% in 19 s; Ubanim at 2.1 x terrain 1.3 won)
    fb.op('JSLte', a=jmin, b=b.const('i32', 0), offset='jlog')
    e = fb.reg(cx.t('f64'))
    fb.op('Mul', dst=e, a=h, b=_ratio(fb, b, SITE_REQ))
    fb.op('SDiv', dst=e, a=e, b=tf)
    fb.op('JSGte', a=m, b=e, offset='sgo')
    wn = fb.reg(cx.t('i32'))
    fb.op('Mov', dst=wn, src=b.field(res, 'length'))
    b.loop_head('jw_pop')
    fb.op('JSLte', a=b.field(res, 'length'), b=b.const('i32', 0), offset='jw_log')
    b.call('hl.types.ArrayObj.pop', res)
    fb.op('JAlways', offset='jw_pop')
    fb.label('jw_log')
    _throttle(fb, b, cx, 'sweak', st, PICK_LOG_T, 'done')
    _log_ev(fb, b, cx, helpers, 'sweak', [('f', fb.get(fac, 'kind')), ('tgt', s), ('n', wn), ('H', h), ('M', m),
                                          ('tf%', tf)])
    fb.op('JAlways', offset='done')
    # passed: `sgo` (armies only, tf 1 at a sietch / renegade base) to check against the strike's `sact` / outcome
    fb.label('sgo')
    _throttle(fb, b, cx, 'sgo', st, PICK_LOG_T, 'jlog')
    _log_ev(fb, b, cx, helpers, 'sgo', [('f', fb.get(fac, 'kind')), ('tgt', s), ('n', b.field(res, 'length')), ('H', h),
                                        ('M', m), ('tf%', tf)])
    fb.label('jlog')
    fb.op('JSLte', a=added, b=b.const('i32', 0), offset='done')
    _log_ev(fb, b, cx, helpers, 'join', [('f', fb.get(fac, 'kind')), ('tgt', s), ('sel', n0), ('add', added),
                                         ('req%', req), ('H', h), ('M', m), ('tf%', tf)])
    fb.label('done')
    fb.end_try(guard2)
    # 3. army floor: a sietch / renegade base always spawns its whole garrison (SIETCH_ARMIES 8 / RENEGADE_ARMIES 10
    # defenders); fewer armies than that are each fought by more than one (Smugglers' 8 armies, half of them 20k
    # Sneaks / Demos, lost Bur-Al'ur's sietch at est 1.32): a short pick is emptied (vanilla: not enough armies)
    # Simulated picks (tryArmyAction after an empty real pick: all our armies + recruits): non-empty = NotEnoughArmies
    # (wait for busy armies), empty = ArmyNotStrongEnough (vanilla requests recruitment). A short simulated pick stays
    # only when we own at least the floor's count of armies, else it is emptied too: with fewer armies than the
    # garrison, waiting would never end and nothing would be recruited
    guard3 = fb.try_()
    fb.op('JNull', reg=res, offset='fl_done')
    fes, _ = _vfield(fb, b, 1, 'enemyStructure')
    fb.op('JNull', reg=fes, offset='fl_done')
    fst = b.cast(fb.dyn(fes), 'ent.Structure')
    fb.op('JNull', reg=fst, offset='fl_done')
    fmin = fb.reg(cx.t('i32'))
    fb.op('Mov', dst=fmin, src=b.const('i32', SIETCH_ARMIES))
    fb.op('JTrue', cond=b.call('ent.Structure.isSietch', fst), offset='fl_chk')
    fb.op('JFalse', cond=b.call('ent.Structure.isRenegadeBase', fst), offset='fl_done')
    fb.op('Mov', dst=fmin, src=b.const('i32', RENEGADE_ARMIES))
    fb.label('fl_chk')
    fn = fb.reg(cx.t('i32'))
    fb.op('Mov', dst=fn, src=b.field(res, 'length'))
    fb.op('JSLte', a=fn, b=b.const('i32', 0), offset='fl_done')
    fb.op('JSGte', a=fn, b=fmin, offset='fl_done')
    fb.op('JFalse', cond=sim, offset='fl_empty')
    fcu, _ = _vfield(fb, b, 1, 'consideredUnits')
    fb.op('JNull', reg=fcu, offset='fl_empty')
    fca = fb.reg(cx.t('hl.types.ArrayObj'))
    fb.op('SafeCast', dst=fca, src=fb.dyn(fcu))
    fb.op('JNull', reg=fca, offset='fl_empty')
    fcn, fci = fb.reg(cx.t('i32')), fb.reg(cx.t('i32'))  # fighting armies we own (the list holds harvesters too)
    fb.op('Mov', dst=fcn, src=b.const('i32', 0))
    fa = _army_loop(fb, b, fca, b.field(fca, 'length'), fci, 'fl_c', 'fl_cd')
    fb.op('JNotNull', reg=b.field(fa, 'harvestComponent'), offset='fl_c')
    fb.op('Incr', dst=fcn)
    fb.op('JAlways', offset='fl_c')
    fb.label('fl_cd')
    fb.op('JSGte', a=fcn, b=fmin, offset='fl_done')
    fb.label('fl_empty')
    b.loop_head('fl_pop')
    fb.op('JSLte', a=b.field(res, 'length'), b=b.const('i32', 0), offset='fl_log')
    b.call('hl.types.ArrayObj.pop', res)
    fb.op('JAlways', offset='fl_pop')
    fb.label('fl_log')
    ffac = b.field(b.field(0, 'controller'), 'owner')
    fb.op('JNull', reg=ffac, offset='fl_done')
    _throttle(fb, b, cx, 'sfloor', fst, PICK_LOG_T, 'fl_done')
    _log_ev(fb, b, cx, helpers, 'sfloor', [('f', fb.get(ffac, 'kind')), ('tgt', fst), ('n', fn), ('min', fmin)])
    fb.label('fl_done')
    fb.end_try(guard3)
    # 5. no ground army in the pick (real or simulated): flyers (Unit.isFlying) can't occupy, a ship-only siege stands at
    # the village for good (Harkonnen's H_Ship at Tab-Al'lon, 8+ min): the nearest ground army of consideredUnits is
    # added, else the pick is emptied (vanilla waits / recruits), log `airpick`
    guard5 = fb.try_()
    fb.op('JNull', reg=res, offset='ap_done')
    apn, api = fb.reg(cx.t('i32')), fb.reg(cx.t('i32'))
    fb.op('Mov', dst=apn, src=b.field(res, 'length'))
    fb.op('JSLte', a=apn, b=b.const('i32', 0), offset='ap_done')
    apa = _army_loop(fb, b, res, apn, api, 'ap_l', 'ap_air')
    fb.op('JFalse', cond=b.call('ent.Unit.isFlying', apa), offset='ap_done')  # a ground army: fine
    fb.op('JAlways', offset='ap_l')
    fb.label('ap_air')
    # vanilla adds the nearest idle armies first, so a strong ship alone is picked every time: add the nearest ground
    # army of its own candidates (consideredUnits) instead; empty only when it has none
    gcu, _ = _vfield(fb, b, 1, 'consideredUnits')
    fb.op('JNull', reg=gcu, offset='ap_pop0')
    gca = fb.reg(cx.t('hl.types.ArrayObj'))
    fb.op('SafeCast', dst=gca, src=fb.dyn(gcu))
    fb.op('JNull', reg=gca, offset='ap_pop0')
    ges, _ = _vfield(fb, b, 1, 'enemyStructure')
    fb.op('JNull', reg=ges, offset='ap_pop0')
    gst = fb.reg(cx.t('ent.Entity'))
    fb.op('SafeCast', dst=gst, src=fb.dyn(ges))
    fb.op('JNull', reg=gst, offset='ap_pop0')
    gbest, gd = fb.reg(cx.t('ent.Army')), fb.reg(cx.t('f64'))
    gbd = fb.reg(cx.t('f64'))
    fb.op('Null', dst=gbest)
    fb.op('Mov', dst=gbd, src=b.const('f64', 1 << 30))
    gi = fb.reg(cx.t('i32'))
    ga = _army_loop(fb, b, gca, b.field(gca, 'length'), gi, 'ap_g', 'ap_gd')
    fb.op('JNotNull', reg=b.field(ga, 'harvestComponent'), offset='ap_g')
    fb.op('JTrue', cond=b.call('ent.Unit.isFlying', ga), offset='ap_g')
    fb.op('JTrue', cond=b.call('hl.types.ArrayObj.contains', res, fb.dyn(ga)), offset='ap_g')
    fb.op('JSLte', a=b.call('ent.Army.get_maxSupply', ga), b=b.const('f64', 0), offset='ap_gs')
    fb.op('JSLt', a=b.call('ent.Army.get_supply', ga), b=_ratio(fb, b, SUP_RESERVE), offset='ap_g')
    fb.label('ap_gs')
    fb.op('Mov', dst=gd, src=b.call('ent.Entity.getDistTo', ga, gst))
    fb.op('JSGte', a=gd, b=gbd, offset='ap_g')
    fb.op('Mov', dst=gbd, src=gd)
    fb.op('Mov', dst=gbest, src=ga)
    fb.op('JAlways', offset='ap_g')
    fb.label('ap_gd')
    fb.op('JNull', reg=gbest, offset='ap_pop0')
    b.call('hl.types.ArrayObj.push', res, fb.dyn(gbest))
    fb.op('JAlways', offset='ap_done')
    fb.label('ap_pop0')
    b.loop_head('ap_pop')
    fb.op('JSLte', a=b.field(res, 'length'), b=b.const('i32', 0), offset='ap_log')
    b.call('hl.types.ArrayObj.pop', res)
    fb.op('JAlways', offset='ap_pop')
    fb.label('ap_log')
    afac = b.field(b.field(0, 'controller'), 'owner')
    fb.op('JNull', reg=afac, offset='ap_done')
    aes, _ = _vfield(fb, b, 1, 'enemyStructure')
    fb.op('JNull', reg=aes, offset='ap_done')
    ast = b.cast(fb.dyn(aes), 'ent.Structure')
    fb.op('JNull', reg=ast, offset='ap_done')
    _throttle(fb, b, cx, 'airpick', ast, PICK_LOG_T, 'ap_done')
    _log_ev(fb, b, cx, helpers, 'airpick', [('f', fb.get(afac, 'kind')), ('tgt', ast), ('n', apn), ('sim', fb.dyn(sim))])
    fb.label('ap_done')
    fb.end_try(guard5)
    fb.op('Ret', ret=res)
    w = fb.build()
    new_ids.add(w)
    for op in sites:
        op.df['fun'].value = w
    return {'siege-join': len(sites)}


def build_siege_engage(cx, helpers, pw, threat, cover, militia, terrain, neutral):
    """aimod_sengage(mil, dt), every CHECK s: early Engage for our siege orders (Military on a Structure: vanilla
    Annex/Pillage/Raze/..., `raid`). Vanilla Regroup waits until every order army reached the regroup point, so a
    stack standing next to the target walked away from it towards a far member first (Fremen raid on Tuoron: 5 armies
    36-55 from it went to 85-106 while a 6th came from home); siege-join makes far members common. An order in
    Regroup moves on to Engage (nextPhase) once its armies within ENGAGE_R of the target (+ our turret cover x
    OWN_COVER_ATK; none and terrain 1 at a sietch / renegade base) have
    ENTER (NEUTRAL_REQ for a neutral target, EARLY_REQ in the opening, as at launch) x (at-war threat within LOCAL + enemy turret cover +
    militia) / terrain, and at least one army is there; the others walk straight in (policy §4 Gathering). Only
    armies at the target count: armies strung out within LOCAL walked in one by one, the weakest first (Harkonnen
    raid on Har-Al'sud lost H_Demo 2v3 before its third army arrived). Logs `sengage`. In a trap: nothing on error."""
    fb = FB(cx, [cx.t('logic.ai.AIMilitary'), cx.t('f64')], cx.t('void'))
    b = B(fb)
    void = fb.reg(cx.t('void'))
    guard = fb.try_()
    ctrl = b.field(0, 'controller')
    fac = b.field(ctrl, 'owner')
    fb.op('JNull', reg=fac, offset='end')
    t = b.field(_state(fb, b, cx), 'time')
    _tick(fb, b, cx, t, CHECK, 'end')
    orders = b.field(b.field(ctrl, 'aiOrders'), 'orders')
    fb.op('JNull', reg=orders, offset='end')
    on = b.field(orders, 'length')
    zi, zero = b.const('i32', 0), b.const('f64', 0)
    local, at = b.const('f64', LOCAL), b.const('f64', ENGAGE_R)
    enter, nreq = _ratio(fb, b, ENTER), _ratio(fb, b, NEUTRAL_REQ)
    t_false, t_true = fb.reg(cx.t('bool')), fb.reg(cx.t('bool'))
    fb.op('Bool', dst=t_false, value=False)
    fb.op('Bool', dst=t_true, value=True)
    no_arr = fb.reg(cx.t('hl.types.ArrayObj'))
    fb.op('Null', dst=no_arr)
    i, j, idx, near = (fb.reg(cx.t('i32')) for _ in range(4))
    h, m, p, q, tf, req = (fb.reg(cx.t('f64')) for _ in range(6))
    se = fb.reg(cx.t('ent.Entity'))
    fb.op('Mov', dst=i, src=zi)
    b.loop_head('o')
    fb.op('JSGte', a=i, b=on, offset='end')
    o = b.cast(b.call('hl.types.ArrayObj.getDyn', orders, i), 'logic.ai.AIOrder')
    fb.op('Incr', dst=i)
    fb.op('JNull', reg=o, offset='o')
    fb.op('JNotEq', a=b.field(o, 'phase'), b=b.const('i32', REGROUP), offset='o')
    fb.op('EnumIndex', dst=idx, value=b.field(o, 'type'))
    fb.op('JNotEq', a=idx, b=b.const('i32', MILITARY), offset='o')
    tt = b.field(o, 'targetType')
    fb.op('JNull', reg=tt, offset='o')
    fb.op('EnumIndex', dst=idx, value=tt)
    fb.op('JNotEq', a=idx, b=b.const('i32', T_STRUCT), offset='o')
    tg = b.call('logic.ai.AIOrder.getTarget', o)
    fb.op('JNull', reg=tg, offset='o')
    s = b.cast(fb.dyn(tg), 'ent.Structure')
    fb.op('Mov', dst=se, src=s)
    units = b.field(o, 'units')
    fb.op('JNull', reg=units, offset='o')
    un = b.field(units, 'length')
    # ours near the target (+ our cover there, x OWN_COVER_ATK; none at a sietch / renegade base)
    fb.op('CallN', dst=m, fun=cover, args=[fac, se, se, t_true, no_arr])
    _atk_cover(fb, b, m, s)
    fb.op('Mov', dst=near, src=zi)
    u = _army_loop(fb, b, units, un, j, 'u', 'udone')
    fb.op('JSGt', a=b.call('ent.Entity.getDistTo', u, se), b=at, offset='u')
    fb.op('Call1', dst=p, fun=pw, arg0=u)
    fb.op('Add', dst=m, a=m, b=p)
    fb.op('Incr', dst=near)
    fb.op('JAlways', offset='u')
    fb.label('udone')
    fb.op('JSLte', a=near, b=zi, offset='o')
    # theirs: at-war armies in reach, turrets covering it (its own go silent under siege), its militia
    fb.op('Call3', dst=h, fun=threat, arg0=fac, arg1=se, arg2=local)
    fb.op('CallN', dst=q, fun=cover, args=[fac, se, se, t_false, no_arr])
    fb.op('Add', dst=h, a=h, b=q)
    fb.op('Call1', dst=q, fun=militia, arg0=s)
    fb.op('Add', dst=h, a=h, b=q)
    fb.op('Call3', dst=q, fun=neutral, arg0=fac, arg1=se, arg2=local)  # other raiders at it fight us too
    fb.op('Add', dst=h, a=h, b=q)
    fb.op('Call2', dst=tf, fun=terrain, arg0=fac, arg1=b.call('ent.Entity.get_zone', se))
    _strong_tf(fb, b, tf, s)
    fb.op('Mov', dst=req, src=enter)
    fb.op('JNotNull', reg=b.call('ent.Entity.get_owner', se), offset='owned')
    fb.op('Mov', dst=req, src=nreq)
    fb.op('JTrue', cond=b.call('ent.Structure.isSietch', s), offset='strong')
    fb.op('JFalse', cond=b.call('ent.Structure.isRenegadeBase', s), offset='nrb')
    fb.label('strong')
    fb.op('Mov', dst=req, src=_ratio(fb, b, SITE_REQ))  # a renegade base or a sietch: SITE_REQ, as at launch (siege-join)
    fb.op('JAlways', offset='owned')
    fb.label('nrb')
    fb.op('JSGte', a=b.field(b.call('ent.Faction.getVillages', fac), 'length'), b=b.const('i32', EARLY_VILLAGES),
          offset='owned')
    fb.op('Mov', dst=req, src=_ratio(fb, b, EARLY_REQ))  # opening (as at launch)
    fb.label('owned')
    _nbump(fb, b, cx, fac, se, req)  # a neutral village whose militia beat us lately (as at launch)
    fb.op('Mul', dst=q, a=h, b=req)
    fb.op('SDiv', dst=q, a=q, b=tf)
    # part of the order still on the way: PART_X x that, else wait (re-judged every CHECK s as they arrive)
    fb.op('JSGte', a=near, b=un, offset='all')
    fb.op('Mul', dst=q, a=q, b=_ratio(fb, b, PART_X))
    fb.label('all')
    fb.op('JSLt', a=m, b=q, offset='o')
    fb.op('Call1', dst=void, fun=helpers.get('nextPhase', cx.fn('logic.ai.AIOrder.nextPhase').findex.value), arg0=o)
    _log_ev(fb, b, cx, helpers, 'sengage', [('f', fb.get(fac, 'kind')), ('tgt', se), ('H', h), ('M', m),
                                            ('near', near), ('n', un), ('tf%', tf)])
    fb.op('JAlways', offset='o')
    fb.label('end')
    fb.end_try(guard)
    fb.op('Ret', ret=void)
    return fb.build()
