"""Siege position: capture from the side of the village away from enemy turrets, and don't chase into them.

Vanilla walks a siege army to the nearest point of the occupation range and micro chases whatever attacks it:
Fremen took Atreides' Sadnin (113 from Arrakeen) with 10 armies standing on its north side, 90-110 from the main
base guns, and lost 6 of them while the order's own balance read 2-13 (winning); one F_Trooper chased a defender to
38 from Arrakeen. F_Special_2, 46 south of Sadnin (159 from Arrakeen), stayed at 100 hp the whole fight.

Every SPOS_T_CHECK s per faction: our Military orders with a Structure target in Action (any army within SPOS_R of
the target) or Engage (armies within SPOS_IN: never pulls a walker forward): an army covered by at-war turrets other
than the target's (aimod_cover, own false, target excluded) is moved (doAction Move, at most every SPOS_T s per army)
to P = target + SPOS_OFF away from the nearest at-war structure E (not the target): still in the occupation range,
farther from E's guns. Not if P is no farther from E than the army already is. Map `sposm` army -> time (desert-step
leaves such an army alone for SPOS_T x 2). Logs `spos` (a, tgt, e, d to P) once per army per 15 s. In a trap."""
from rules.common import *  # noqa: F401,F403  thresholds (AI-POLICY §4) and bytecode helpers
from rules.worm import _move_to


def build_spos(cx, helpers, cover):
    """aimod_spos(mil, dt) (see module doc)."""
    fb = FB(cx, [cx.t('logic.ai.AIMilitary'), cx.t('f64')], cx.t('void'))
    b = B(fb)
    void = fb.reg(cx.t('void'))
    guard = fb.try_()
    ctrl = b.field(0, 'controller')
    fac = b.field(ctrl, 'owner')
    fb.op('JNull', reg=fac, offset='end')
    t = fb.reg(cx.t('f64'))
    fb.op('Mov', dst=t, src=b.field(_state(fb, b, cx), 'time'))
    _tick(fb, b, cx, t, SPOS_CHECK, 'end')
    orders = b.field(b.field(ctrl, 'aiOrders'), 'orders')
    fb.op('JNull', reg=orders, offset='end')
    state = _state(fb, b, cx)
    facs = b.cast(fb.get(state, 'factions', 'array'), 'hl.types.ArrayObj')
    fb.op('JNull', reg=facs, offset='end')
    sposm = _global_map(fb, b, cx, 'sposm')
    zi = b.const('i32', 0)
    i, j, k, l, idx, ph = (fb.reg(cx.t('i32')) for _ in range(6))
    d, lim, cv, bd, dx, dy, q, px, py = (fb.reg(cx.t('f64')) for _ in range(9))
    tgt, ee, ae = fb.reg(cx.t('ent.Entity')), fb.reg(cx.t('ent.Entity')), fb.reg(cx.t('ent.Entity'))
    f_false, no_arr = fb.reg(cx.t('bool')), fb.reg(cx.t('hl.types.ArrayObj'))
    fb.op('Bool', dst=f_false, value=False)
    fb.op('Null', dst=no_arr)
    fb.op('Mov', dst=i, src=b.field(orders, 'length'))
    b.loop_head('o')
    fb.op('JSLte', a=i, b=zi, offset='end')
    fb.op('Sub', dst=i, a=i, b=b.const('i32', 1))
    o = b.cast(b.call('hl.types.ArrayObj.getDyn', orders, i), 'logic.ai.AIOrder')
    fb.op('JNull', reg=o, offset='o')
    fb.op('EnumIndex', dst=idx, value=b.field(o, 'type'))
    fb.op('JNotEq', a=idx, b=b.const('i32', MILITARY), offset='o')
    tt = b.field(o, 'targetType')
    fb.op('JNull', reg=tt, offset='o')
    fb.op('EnumIndex', dst=idx, value=tt)
    fb.op('JNotEq', a=idx, b=b.const('i32', T_STRUCT), offset='o')
    fb.op('Mov', dst=ph, src=b.field(o, 'phase'))
    fb.op('Mov', dst=lim, src=b.const('f64', SPOS_R))
    fb.op('JEq', a=ph, b=b.const('i32', ACTION), offset='plim')
    fb.op('JNotEq', a=ph, b=b.const('i32', REGROUP + 1), offset='o')
    fb.op('Mov', dst=lim, src=b.const('f64', SPOS_IN))
    fb.label('plim')
    fb.op('Mov', dst=tgt, src=b.cast(b.call('logic.ai.AIOrder.getTarget', o), 'ent.Entity'))
    fb.op('JNull', reg=tgt, offset='o')
    units = b.field(o, 'units')
    fb.op('JNull', reg=units, offset='o')
    un = b.field(units, 'length')
    a = _army_loop(fb, b, units, un, j, 'a', 'o')
    fb.op('Mov', dst=ae, src=a)
    fb.op('JSGt', a=b.call('ent.Entity.getDistTo', ae, tgt), b=lim, offset='a')
    fb.op('CallN', dst=cv, fun=cover, args=[fac, ae, tgt, f_false, no_arr])
    fb.op('JSLte', a=cv, b=b.const('f64', 0), offset='a')
    # nearest at-war structure (not the target): the guns to step away from
    fb.op('Null', dst=ee)
    fb.op('Mov', dst=bd, src=b.const('f64', 1 << 30))
    fb.op('Mov', dst=k, src=zi)
    b.loop_head('f')
    fb.op('JSGte', a=k, b=b.field(facs, 'length'), offset='fdone')
    of = b.cast(b.call('hl.types.ArrayObj.getDyn', facs, k), 'ent.Faction')
    fb.op('Incr', dst=k)
    fb.op('JNull', reg=of, offset='f')
    fb.op('JEq', a=of, b=fac, offset='f')
    fb.op('JFalse', cond=b.call('logic.state.State.areAtWar', state, fac, of), offset='f')
    ss = b.cast(fb.get(of, 'structures', 'array'), 'hl.types.ArrayObj')
    fb.op('JNull', reg=ss, offset='f')
    fb.op('Mov', dst=l, src=zi)
    b.loop_head('g')
    fb.op('JSGte', a=l, b=b.field(ss, 'length'), offset='f')
    se = b.cast(b.call('hl.types.ArrayObj.getDyn', ss, l), 'ent.Entity')
    fb.op('Incr', dst=l)
    fb.op('JNull', reg=se, offset='g')
    fb.op('JEq', a=se, b=tgt, offset='g')
    fb.op('Mov', dst=d, src=b.call('ent.Entity.getDistTo', ae, se))
    fb.op('JSGte', a=d, b=bd, offset='g')
    fb.op('Mov', dst=bd, src=d)
    fb.op('Mov', dst=ee, src=se)
    fb.op('JAlways', offset='g')
    fb.label('fdone')
    fb.op('JNull', reg=ee, offset='a')
    # P = target + SPOS_OFF along (target - E)
    fb.op('Sub', dst=dx, a=b.field(tgt, 'posx'), b=b.field(ee, 'posx'))
    fb.op('Sub', dst=dy, a=b.field(tgt, 'posy'), b=b.field(ee, 'posy'))
    fb.op('Mul', dst=q, a=dx, b=dx)
    fb.op('Mul', dst=d, a=dy, b=dy)
    fb.op('Add', dst=q, a=q, b=d)
    fb.op('JSLte', a=q, b=b.const('f64', 1), offset='a')
    fb.op('Mov', dst=q, src=b.call('hxd.$Math.sqrt', q))
    off = b.const('f64', SPOS_OFF)
    fb.op('Mul', dst=px, a=dx, b=off)
    fb.op('SDiv', dst=px, a=px, b=q)
    fb.op('Add', dst=px, a=px, b=b.field(tgt, 'posx'))
    fb.op('Mul', dst=py, a=dy, b=off)
    fb.op('SDiv', dst=py, a=py, b=q)
    fb.op('Add', dst=py, a=py, b=b.field(tgt, 'posy'))
    # only if P is farther from E than the army is now (else nothing to gain)
    fb.op('Sub', dst=dx, a=px, b=b.field(ee, 'posx'))
    fb.op('Sub', dst=dy, a=py, b=b.field(ee, 'posy'))
    fb.op('Mul', dst=dx, a=dx, b=dx)
    fb.op('Mul', dst=dy, a=dy, b=dy)
    fb.op('Add', dst=dx, a=dx, b=dy)
    fb.op('Mov', dst=dx, src=b.call('hxd.$Math.sqrt', dx))
    fb.op('Sub', dst=dx, a=dx, b=b.const('f64', 10))
    fb.op('JSLte', a=dx, b=bd, offset='a')
    _throttle(fb, b, cx, 'spos', a, SPOS_T, 'a')
    b.call('haxe.ds.ObjectMap.set', sposm, fb.dyn(a), fb.dyn(t))
    ok = _move_to(fb, b, cx, a, px, py, fac)
    _throttle(fb, b, cx, 'sposlog', a, 15, 'a')
    _log_ev(fb, b, cx, helpers, 'spos', [('f', fb.get(fac, 'kind')), ('a', a), ('tgt', tgt), ('e', ee),
                                         ('cv', cv), ('ok', ok)])
    fb.op('JAlways', offset='a')
    fb.label('end')
    fb.end_try(guard)
    fb.op('Ret', ret=void)
    return fb.build()
