"""Contact tension (AI-POLICY §5c): villages within one turret range of another faction's (or a neutral) village are
contact points worth more than their production; this module measures how long and how hard each one has rubbed.

The failure: Aid-Al'ha (neutral) and Atreides' Qal-nit stand ~85 apart. Fremen captured Aid-Al'ha unopposed while
Atreides gathered in `rally` (contest entry 1.5x not met), then both sides froze, each refusing to raid the other's
village every 30 s.

Tick (every TEN_T s per faction): for each of our villages V on our land (not a main base), the nearest village W
within TEN_R that isn't ours and isn't a main base is its contact partner (maps `tenw` V -> W, `tenv` V -> T).
T rises TEN_UP x closeness (1 at d <= TEN_NEAR, linearly down to TEN_FAR_W at TEN_R) x TEN_HOT (2) while anyone
besieges W or at-war armies stand within COVER_R of V; without a partner it falls TEN_DOWN per tick (entry removed
at 0). Logs `tension` (V, W, T x100, d) for the faction's hottest pair once per TEN_LOG s.
Query aimod_tension(fac, W) -> the highest T of our villages whose partner is W (0 if none). Read-only for the
other rules: at tension 0 nothing changes anywhere. In a trap."""
from rules.common import *  # noqa: F401,F403  thresholds (AI-POLICY §4) and bytecode helpers


def build_tension(cx):
    """aimod_tension(fac, w) -> f64 (see module doc)."""
    fb = FB(cx, [cx.t('ent.Faction'), cx.t('ent.Entity')], cx.t('f64'))
    b = B(fb)
    res = fb.reg(cx.t('f64'))
    fb.op('Mov', dst=res, src=b.const('f64', 0))
    guard = fb.try_()
    fb.op('JNull', reg=0, offset='end')
    fb.op('JNull', reg=1, offset='end')
    tenw, tenv = _global_map(fb, b, cx, 'tenw'), _global_map(fb, b, cx, 'tenv')
    mine = b.cast(fb.get(0, 'structures', 'array'), 'hl.types.ArrayObj')
    fb.op('JNull', reg=mine, offset='end')
    i = fb.reg(cx.t('i32'))
    q = fb.reg(cx.t('f64'))
    fb.op('Mov', dst=i, src=b.const('i32', 0))
    b.loop_head('s')
    fb.op('JSGte', a=i, b=b.field(mine, 'length'), offset='end')
    s = b.call('hl.types.ArrayObj.getDyn', mine, i)
    fb.op('Incr', dst=i)
    fb.op('JNull', reg=s, offset='s')
    fb.op('JNotEq', a=b.call('haxe.ds.ObjectMap.get', tenw, s), b=fb.dyn(1), offset='s')
    tv = b.call('haxe.ds.ObjectMap.get', tenv, s)
    fb.op('JNull', reg=tv, offset='s')
    fb.op('SafeCast', dst=q, src=tv)
    fb.op('JSLte', a=q, b=res, offset='s')
    fb.op('Mov', dst=res, src=q)
    fb.op('JAlways', offset='s')
    fb.label('end')
    fb.end_try(guard)
    fb.op('Ret', ret=res)
    return fb.build()


def build_tension_tick(cx, helpers, threat):
    """aimod_tension_tick(mil, dt) (see module doc)."""
    fb = FB(cx, [cx.t('logic.ai.AIMilitary'), cx.t('f64')], cx.t('void'))
    b = B(fb)
    void = fb.reg(cx.t('void'))
    guard = fb.try_()
    fac = b.field(b.field(0, 'controller'), 'owner')
    fb.op('JNull', reg=fac, offset='end')
    state = _state(fb, b, cx)
    t = fb.reg(cx.t('f64'))
    fb.op('Mov', dst=t, src=b.field(state, 'time'))
    _tick(fb, b, cx, t, TEN_T, 'end')
    villages = b.field(state, 'villages')
    fb.op('JNull', reg=villages, offset='end')
    mine = b.cast(fb.get(fac, 'structures', 'array'), 'hl.types.ArrayObj')
    fb.op('JNull', reg=mine, offset='end')
    tenw, tenv = _global_map(fb, b, cx, 'tenw'), _global_map(fb, b, cx, 'tenv')
    teno = _global_map(fb, b, cx, 'teno')
    zi = b.const('i32', 0)
    i, j = fb.reg(cx.t('i32')), fb.reg(cx.t('i32'))
    d, bd, tv, inc, hot_t, hot_d = (fb.reg(cx.t('f64')) for _ in range(6))
    ve, we, bw, hot_v, hot_w = (fb.reg(cx.t('ent.Entity')) for _ in range(5))
    fb.op('Mov', dst=hot_t, src=b.const('f64', 0))
    fb.op('Mov', dst=hot_d, src=b.const('f64', 0))
    fb.op('Null', dst=hot_v)
    fb.op('Null', dst=hot_w)
    fb.op('Mov', dst=i, src=zi)
    b.loop_head('v')
    fb.op('JSGte', a=i, b=b.field(mine, 'length'), offset='vdone')
    v = b.cast(b.call('hl.types.ArrayObj.getDyn', mine, i), 'ent.Structure')
    fb.op('Incr', dst=i)
    fb.op('JNull', reg=v, offset='v')
    fb.op('JTrue', cond=b.call('ent.Structure.get_isMainBase', v), offset='v')
    fb.op('Mov', dst=ve, src=v)
    vz = b.call('ent.Entity.get_zone', ve)
    fb.op('JNull', reg=vz, offset='v')
    fb.op('JNotEq', a=b.field(vz, 'owner'), b=fac, offset='v')  # on our land (not a UW HQ in someone's village)
    # nearest foreign / neutral village within TEN_R
    fb.op('Null', dst=bw)
    fb.op('Mov', dst=bd, src=b.const('f64', TEN_R))
    fb.op('Mov', dst=j, src=zi)
    b.loop_head('w')
    fb.op('JSGte', a=j, b=b.field(villages, 'length'), offset='wdone')
    w = b.cast(b.call('hl.types.ArrayObj.getDyn', villages, j), 'ent.Structure')
    fb.op('Incr', dst=j)
    fb.op('JNull', reg=w, offset='w')
    fb.op('Mov', dst=we, src=w)
    fb.op('JEq', a=we, b=ve, offset='w')
    fb.op('JEq', a=b.call('ent.Entity.get_owner', we), b=fac, offset='w')
    fb.op('JTrue', cond=b.call('ent.Structure.get_isMainBase', w), offset='w')
    fb.op('Mov', dst=d, src=b.call('ent.Entity.getDistTo', ve, we))
    fb.op('JSGt', a=d, b=bd, offset='w')
    fb.op('Mov', dst=bd, src=d)
    fb.op('Mov', dst=bw, src=we)
    fb.op('JAlways', offset='w')
    fb.label('wdone')
    fb.op('Mov', dst=tv, src=b.const('f64', 0))
    old = b.call('haxe.ds.ObjectMap.get', tenv, fb.dyn(ve))
    fb.op('JNull', reg=old, offset='hasold')
    # a village that changed hands starts at 0 for its new owner (map `teno` V -> owner)
    fb.op('JNotEq', a=b.call('haxe.ds.ObjectMap.get', teno, fb.dyn(ve)), b=fb.dyn(fac), offset='hasold')
    fb.op('SafeCast', dst=tv, src=old)
    fb.label('hasold')
    b.call('haxe.ds.ObjectMap.set', teno, fb.dyn(ve), fb.dyn(fac))
    fb.op('JNotNull', reg=bw, offset='rise')
    # no partner: cool down
    fb.op('Sub', dst=tv, a=tv, b=_ratio(fb, b, TEN_DOWN))
    fb.op('JSGt', a=tv, b=b.const('f64', 0), offset='keep')
    b.call('haxe.ds.ObjectMap.remove', tenv, fb.dyn(ve))
    b.call('haxe.ds.ObjectMap.remove', tenw, fb.dyn(ve))
    fb.op('JAlways', offset='v')
    fb.label('keep')
    b.call('haxe.ds.ObjectMap.set', tenv, fb.dyn(ve), fb.dyn(tv))
    fb.op('JAlways', offset='v')
    # partner: closeness = 1 at d <= TEN_NEAR, down to TEN_FAR_W at TEN_R
    fb.label('rise')
    fb.op('Sub', dst=inc, a=b.const('f64', TEN_R), b=bd)
    fb.op('SDiv', dst=inc, a=inc, b=b.const('f64', TEN_R - TEN_NEAR))
    fb.op('JSLte', a=inc, b=b.const('f64', 1), offset='c1')
    fb.op('Mov', dst=inc, src=b.const('f64', 1))
    fb.label('c1')
    fb.op('Mul', dst=inc, a=inc, b=_ratio(fb, b, 1 - TEN_FAR_W))
    fb.op('Add', dst=inc, a=inc, b=_ratio(fb, b, TEN_FAR_W))
    fb.op('Mul', dst=inc, a=inc, b=_ratio(fb, b, TEN_UP))
    # hot: anyone besieges W, or at-war armies stand at V
    sg = b.field(b.cast(bw, 'ent.Structure'), 'siege')
    fb.op('JNull', reg=sg, offset='cold')
    fb.op('JNotNull', reg=b.field(sg, 'besiegingFaction'), offset='hot')
    fb.label('cold')
    fb.op('Call3', dst=d, fun=threat, arg0=fac, arg1=ve, arg2=b.const('f64', COVER_R))
    fb.op('JSLte', a=d, b=b.const('f64', 0), offset='add')
    fb.label('hot')
    fb.op('Mul', dst=inc, a=inc, b=b.const('f64', TEN_HOT))
    fb.label('add')
    fb.op('Add', dst=tv, a=tv, b=inc)
    fb.op('JSLte', a=tv, b=b.const('f64', 1), offset='cap')
    fb.op('Mov', dst=tv, src=b.const('f64', 1))
    fb.label('cap')
    b.call('haxe.ds.ObjectMap.set', tenv, fb.dyn(ve), fb.dyn(tv))
    b.call('haxe.ds.ObjectMap.set', tenw, fb.dyn(ve), fb.dyn(bw))
    fb.op('JSLte', a=tv, b=hot_t, offset='v')
    fb.op('Mov', dst=hot_t, src=tv)
    fb.op('Mov', dst=hot_d, src=bd)
    fb.op('Mov', dst=hot_v, src=ve)
    fb.op('Mov', dst=hot_w, src=bw)
    fb.op('JAlways', offset='v')
    fb.label('vdone')
    fb.op('JNull', reg=hot_v, offset='end')
    _throttle(fb, b, cx, 'tenlog', fac, TEN_LOG, 'end')
    _log_ev(fb, b, cx, helpers, 'tension', [('f', fb.get(fac, 'kind')), ('v', hot_v), ('w', hot_w), ('T%', hot_t),
                                            ('d', hot_d)])
    fb.label('end')
    fb.end_try(guard)
    fb.op('Ret', ret=void)
    return fb.build()
